### PR TITLE
Make deploy tasks mutually exclusive

### PR DESCRIPTION
**Pull request by johlju**
# Pull Request

### Changed
- The Deploy tasks `publish_nupkg_to_gallery` and `publish_module_to_gallery`
  are now made mutually exclusive. For each deploy pipeline you must choose
  to use either one. 
  - `publish_nupkg_to_gallery` is using `nuget` to publish to the gallery.
  - `publish_module_to_gallery` is using the cmdlet `Publish-Module` to
    publish to the gallery.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/217)

### CODE REVIEW

**Comment by gaelcolas** [comment]
Gonna check tonight. Ta

**Review by gaelcolas — APPROVED** [review]

**Comment by gaelcolas** [comment]
Waiting for the build, I think there's one extra line in changelog I can't remove from my phone.

**Comment by johlju** [comment]
Yes I see it, will fix directy.

**Comment by johlju** [comment]
Fixed. 🙂

**Pull request merged**
