### PR TITLE
Don't fail when there's no project name 

### PR DESCRIPTION
**Pull request by gaelcolas**
# Pull Request

### Changed

- Making sure the `Set-SamplerTaskVariable` does not fail when there's no Module manifest (i.e. when using Sampler for other reasons than building a module).

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/331)

### CODE REVIEW

**Comment by gaelcolas** [comment]
This PR is in preparation of a bigger PR that will use this fix/feature.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/331)* status: all files reviewed, 2 unresolved discussions (waiting on @gaelcolas)

___
*[.build/tasks/release.module.build.ps1, line 139 at r3](https://reviewable.io/reviews/gaelcolas/sampler/331#-MkhHQPZ84t-85EOzA0E:-MkhHQPZ84t-85EOzA0F:bill87i) ([raw file](https://github.com/gaelcolas/sampler/blob/5db886d292cebf86188f72fc64f71f145c3e60d2/.build/tasks/release.module.build.ps1#L139)):*
> ```
> No Project Name found
> ```

Can we change this to "No PowerShell module name found" to be more clear since other types of builds will still have some kind of project name.
___
*[Sampler/scripts/Set-SamplerTaskVariable.ps1, line 132 at r3](https://reviewable.io/reviews/gaelcolas/sampler/331#-MkhI3e40ZDj0gdeEDiJ:-MkhI3e40ZDj0gdeEDiK:bn3q1q2) ([raw file](https://github.com/gaelcolas/sampler/blob/5db886d292cebf86188f72fc64f71f145c3e60d2/Sampler/scripts/Set-SamplerTaskVariable.ps1#L132)):*
> ```
> "The ProjectName wasn't found. This might be because you are not build PowerShell module, in which case you can ignore this message."
> ```

Can we change to (fix grammar too):

```
Write-Warning -Message "No PowerShell module name found. This might be because you are not building a PowerShell module, in which case you can ignore this message."
```

**Review by gaelcolas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/331)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[.build/tasks/release.module.build.ps1, line 139 at r3](https://reviewable.io/reviews/gaelcolas/sampler/331#-MkhHQPZ84t-85EOzA0E:-MkkNJIREWovOTfMoeIv:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/5db886d292cebf86188f72fc64f71f145c3e60d2/.build/tasks/release.module.build.ps1#L139)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> No Project Name found
> ```

Can we change this to "No PowerShell module name found" to be more clear since other types of builds will still have some kind of project name.
</blockquote></details>

Done.
___
*[Sampler/scripts/Set-SamplerTaskVariable.ps1, line 132 at r3](https://reviewable.io/reviews/gaelcolas/sampler/331#-MkhI3e40ZDj0gdeEDiJ:-MkkNKgU3r11ieX-WIDD:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/5db886d292cebf86188f72fc64f71f145c3e60d2/Sampler/scripts/Set-SamplerTaskVariable.ps1#L132)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "The ProjectName wasn't found. This might be because you are not build PowerShell module, in which case you can ignore this message."
> ```

Can we change to (fix grammar too):

```
Write-Warning -Message "No PowerShell module name found. This might be because you are not building a PowerShell module, in which case you can ignore this message."
```
</blockquote></details>

Done.

**Review by gaelcolas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/331)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[Sampler/scripts/Set-SamplerTaskVariable.ps1, line 132 at r3](https://reviewable.io/reviews/gaelcolas/sampler/331#-MkhI3e40ZDj0gdeEDiJ:-MkkNUDwATanmH_aOEdF:bdifvai) ([raw file](https://github.com/gaelcolas/sampler/blob/5db886d292cebf86188f72fc64f71f145c3e60d2/Sampler/scripts/Set-SamplerTaskVariable.ps1#L132)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I've also removed the Write-Warning as it should just be output.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/331#-:-Mkwg7N08Z8BSH14EFGR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaelcolas)

**Pull request merged**
