### PR TITLE
Updated PesterScript to accept hashtables

### PR DESCRIPTION
**Pull request by ykuijs**
# Pull Request

## Pull Request (PR) description

Updated the PesterScript parameter to allow the specification of hastables, to enable specifying parameters to Pester.

E.g.: 
```PowerShell
$path16 = '$path16 = "C:\src\SharePointDsc\Tests\Unit\Stubs\SharePoint\16.0.4456.1000\Microsoft.SharePoint.PowerShell.psm1"'
.\build.ps1 -Tasks test -PesterScript @{ Path =  'C:\src\SharePointDsc\tests\Unit'; Parameters = @{SharePointCmdletModule = $path16 } }
```

### Changed
- Updated the PesterScript parameter to allow the specification of hastables,
  to enable specifying parameters to Pester.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [x] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/117)

### CODE REVIEW

**Comment by ykuijs** [comment]
@gaelcolas Can you please review this PR? I need it to be able to test against multiple versions of SharePoint ;-)

**Comment by johlju** [comment]
@ykuijs sorry for taking so long to review.

**Comment by ykuijs** [comment]
@johlju Ready for a final review.

**Comment by johlju** [comment]
@ykuijs pushing a release with this one in it so you can start using it.

**Pull request merged**
