### PR TITLE
Added task `Set_PSModulePath` for configuring the `PSModulePath`

### PR DESCRIPTION
**Pull request by raandree**
# Pull Request

### Added

- Added task `Set_PSModulePath`.
  - Added function `Set-SamplerPSModulePath`.
  - Added tests for the task and function.
  - Added task `Set_PSModulePath` to `build.yml` Plaster template for project
    type `dsccommunity`.

See details in the `readme.md`.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [x] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/404)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/404)* status: all files reviewed, 4 unresolved discussions (waiting on @raandree)

___
*[`build.yaml` line 185 at r2](https://reviewable.io/reviews/gaelcolas/sampler/404#-NJACpfrBNCtplAXRqCZ:-NJACpfsDccaqjNdF84-:b-ixtade) ([raw file](https://github.com/gaelcolas/sampler/blob/1e1f3b2e706897e9aec421d8b905ef077f9f4958/build.yaml#L185)):*
> ```YAML
>   RemovePersonal: true
>   RemoveProgramFiles: true
>   RemoveWindows: false
> ```

Suggest uncomment SetPSModulePath in Samplers build.yml so that we build and test the Sampler module with the PSModulePath "intact".



_Suggestion:_
```YAML
# Uncomment to modify the PSModulePath in the build pipeline (also requires the task Set_PSModulePath).
#SetPSModulePath:
  #PSModulePath: C:\Users\<UserName>\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;
  #RemovePersonal: true
  #RemoveProgramFiles: true
  #RemoveWindows: false
  #SetSystemDefault: false
```
___
*[`README.md` line 1621 at r2](https://reviewable.io/reviews/gaelcolas/sampler/404#-NJADYnUBhznpvzhXJk2:-NJADYnUBhznpvzhXJk3:b-qrllb5) ([raw file](https://github.com/gaelcolas/sampler/blob/1e1f3b2e706897e9aec421d8b905ef077f9f4958/README.md#L1621)):*
> ```Markdown
> ####################################################
> SetPSModulePath:
>   #PSModulePath: C:\Users\Install\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;c:\Users\Install\.vscode\extensions\ms-vscode.powershell-2022.5.1\modules;
> ```

We can remove the # from this line as it is documentation?



_Suggestion:_
```Markdown
PSModulePath
```
___
*[`Sampler/Templates/Build/build.yaml.template` line 142 at r2](https://reviewable.io/reviews/gaelcolas/sampler/404#-NJAFGA98Zy4zWZgI8HP:-NJAFGA98Zy4zWZgI8HQ:b-ma7m4b) ([raw file](https://github.com/gaelcolas/sampler/blob/1e1f3b2e706897e9aec421d8b905ef077f9f4958/Sampler/Templates/Build/build.yaml.template#L142)):*
> ```
> 
>   # Defining test task to be run when invoking `./build.ps1 -Tasks test`
>   test:
> ```

Suggest adding the task commented out so it is easier for users to opt-in to use the task.



_Suggestion:_
```
  test:
    # Uncomment to modify the PSModulePath in the test pipeline (also requires the build configuration section SetPSModulePath).
    #- Set_PSModulePath
    - Pester_Tests_Stop_On_Fail
    # Use this task if pipeline uses code coverage and the module is using the
    # pattern of Public, Private, Enum, Classes.
    #- Convert_Pester_Coverage
    - Pester_if_Code_Coverage_Under_Threshold
```
___
*[`Sampler/Templates/Build/build.yaml.template` line 362 at r2](https://reviewable.io/reviews/gaelcolas/sampler/404#-NJAEJGR2BBkwdOQf2Zt:-NJAEJGR2BBkwdOQf2Zu:b-u6ulq3) ([raw file](https://github.com/gaelcolas/sampler/blob/1e1f3b2e706897e9aec421d8b905ef077f9f4958/Sampler/Templates/Build/build.yaml.template#L362)):*
> ```
> ####################################################
> SetPSModulePath:
>   #PSModulePath: C:\Users\Install\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;c:\Users\Install\.vscode\extensions\ms-vscode.powershell-2022.5.1\modules;
> ```

Suggest uncomment SetPSModulePath in Samplers build.yml so that the user opt-in to this behaviour.



_Suggestion:_
```
# Uncomment to modify the PSModulePath in the build pipeline (also requires the task Set_PSModulePath).
#SetPSModulePath:
  #PSModulePath: C:\Users\<UserName>\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;c:\Users\<UserName>\.vscode\extensions\ms-vscode.powershell-2022.5.1\modules;
  #RemovePersonal: false
  #RemoveProgramFiles: false
  #RemoveWindows: false
  #SetSystemDefault: false
```

**Comment by johlju** [comment]
I merged a fix for the unrelated test that failed. Should pass on next commit. 🙂

**Review by johlju — COMMENTED** [review]
@raandree can you look at the review comments please?

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/404#-:-NOkKsAT4YIzZOnYDNIX:bvdaezu)* status: all files reviewed, 4 unresolved discussions (waiting on @raandree)

**Review by raandree — COMMENTED** [review]
Thanks, @johlju, all done. Have I missed something?

> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/404#-:-NPPAz7v8sv8qSQugKfw:b-th2nws)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[`build.yaml` line 185 at r2](https://reviewable.io/reviews/gaelcolas/Sampler/404#-NJACpfrBNCtplAXRqCZ:-NPP9GyBAQSvjU7cO9W6:b-896fix) ([raw file](https://github.com/gaelcolas/Sampler/blob/1e1f3b2e706897e9aec421d8b905ef077f9f4958/build.yaml#L185)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Suggest uncomment SetPSModulePath in Samplers build.yml so that we build and test the Sampler module with the PSModulePath "intact".
</blockquote></details>

Done.
___
*[`README.md` line 1621 at r2](https://reviewable.io/reviews/gaelcolas/Sampler/404#-NJADYnUBhznpvzhXJk2:-NPP9S1kBq70a21ymDfA:b-896fix) ([raw file](https://github.com/gaelcolas/Sampler/blob/1e1f3b2e706897e9aec421d8b905ef077f9f4958/README.md#L1621)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove the # from this line as it is documentation?
</blockquote></details>

Done.
___
*[`Sampler/Templates/Build/build.yaml.template` line 142 at r2](https://reviewable.io/reviews/gaelcolas/Sampler/404#-NJAFGA98Zy4zWZgI8HP:-NPP9ljB4QaF-EwuT65e:b-896fix) ([raw file](https://github.com/gaelcolas/Sampler/blob/1e1f3b2e706897e9aec421d8b905ef077f9f4958/Sampler/Templates/Build/build.yaml.template#L142)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Suggest adding the task commented out so it is easier for users to opt-in to use the task.
</blockquote></details>

Done.
___
*[`Sampler/Templates/Build/build.yaml.template` line 362 at r2](https://reviewable.io/reviews/gaelcolas/Sampler/404#-NJAEJGR2BBkwdOQf2Zt:-NPPAuItCPwnOKPrOed-:b-896fix) ([raw file](https://github.com/gaelcolas/Sampler/blob/1e1f3b2e706897e9aec421d8b905ef077f9f4958/Sampler/Templates/Build/build.yaml.template#L362)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Suggest uncomment SetPSModulePath in Samplers build.yml so that the user opt-in to this behaviour.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/404#-:-NPRRVTb8iJdewCGEKeF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @raandree)

**Pull request merged**
