### PR TITLE
Fix issue using Sampler with Windows PowerShell

### PR DESCRIPTION
**Pull request by johlju**
# Pull Request

### Fixed
- Fixed a problem which occurred on certain machined when using Sampler in
  Windows PowerShell. Fixes [#350](https://github.com/gaelcolas/Sampler/issues/350)

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/369)

### CODE REVIEW

**Comment by johlju** [comment]
@nyanhp do you have time to do a quick review?

**Comment by johlju** [comment]
Tests will be added later after we converted this repo to Pester 5 tests.

**Review by nyanhp — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/369)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Review by gaelcolas — APPROVED** [review]
As discussed offline, sounds good.

**Pull request merged**
