### PR TITLE
Extracted Common.Functions.psm1 in single function per file in source

### PR DESCRIPTION
**Pull request by gaelcolas**
# Pull Request

## Pull Request (PR) description
- Extracted the Common functions to be within the main Sampler module to enable re-usability.
- Updated this project's `build.ps1` to load the Private/Public *.ps1 so it can build itselves without impacting Sampler templates.
- Added empty functions' Unit test files (for subsequent PR when writing moving to Pester 5). 
- Added Comment-based help for the extracted functions.
- Dropped the CodeCoverage Threshold of the project to reflect the newly discovered code (`Common.Functions.psm1` wasn't counted for code coverage).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/238)

### CODE REVIEW

**Comment by gaelcolas** [comment]
ohhh this is weird.
It failed on Windows PowerShell because PSUseSingularNouns is failing on `Merge-JaCoCoReports` and `Update-JaCoCoStatistics` which is fine, but why would that fail only on Windows PS and not ALL pwsh?

**Review by johlju — COMMENTED** [review]
> Reviewed 47 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/238)* status: all files reviewed, 1 unresolved discussion (waiting on @gaelcolas)

___
*[.build/tasks/Invoke-Pester.pester.build.ps1, line 81 at r1](https://reviewable.io/reviews/gaelcolas/sampler/238#-MV5VvwR-Cmmh0H4ku_Q:-MV5VvwR-Cmmh0H4ku_R:bca6lc4) ([raw file](https://github.com/gaelcolas/sampler/blob/84af7e13c4d82cff008cdb67824384e622269125/.build/tasks/Invoke-Pester.pester.build.ps1#L81)):*
> ```
> RuntimeCodeCoverageThreshold
> ```

Looks like it should be `CodeCoverageThreshold` and should not have changed.

**Comment by johlju** [comment]
It looks like `PSUseSingularNouns` is not returned from `Get-ScriptAnalyzerRule`, so that rule is only "enabled" on Windows PowerShell for some reason.

PowerShell:
```
C:\source\Sampler [f/functions ≡]> (Get-ScriptAnalyzerRule).Count
63
```

Windows Powershell:
```
C:\source\Sampler [f/functions ≡]> (Get-ScriptAnalyzerRule).Count
64
```

**Comment by johlju** [comment]
Not even this works in PowerShell. It seems it is just skipped.

```powershell
Invoke-ScriptAnalyzer -Path .\Sampler\Public\Merge-JaCoCoReports.ps1 -IncludeRule 'PSUseSingularNouns'
```

**Comment by johlju** [comment]
It is stated here: https://github.com/PowerShell/PSScriptAnalyzer/blob/master/RuleDocumentation/UseSingularNouns.md, and if we are lucky it might be resolved according to issue https://github.com/PowerShell/PSScriptAnalyzer/issues/1626.

**Comment by johlju** [comment]
@gaelcolas initial test shows that this works to build and test locally for the SqlServerDsc module and DscResource.DocGenerator. After this is merged I think we should just verify the preview release with SharePointDsc so it works in the pipeline. It uses functionality that no other module does.

**Review by gaelcolas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/238)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[.build/tasks/Invoke-Pester.pester.build.ps1, line 81 at r1](https://reviewable.io/reviews/gaelcolas/sampler/238#-MV5VvwR-Cmmh0H4ku_Q:-MV6N4cp7abFfNbReqir:bd4mhev) ([raw file](https://github.com/gaelcolas/sampler/blob/84af7e13c4d82cff008cdb67824384e622269125/.build/tasks/Invoke-Pester.pester.build.ps1#L81)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> RuntimeCodeCoverageThreshold
> ```

Looks like it should be `CodeCoverageThreshold` and should not have changed.
</blockquote></details>

I've changed the name of the variable/parameter from the function, to make it clearer which one is taking precedence. So I think this is correct.

**Comment by gaelcolas** [comment]
renamed and updated.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/238#-:-MVAkPj-364QOe0PtlO-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaelcolas)

___
*[.build/tasks/Invoke-Pester.pester.build.ps1, line 81 at r1](https://reviewable.io/reviews/gaelcolas/sampler/238#-MV5VvwR-Cmmh0H4ku_Q:-MVAjd1i4_zxCSopyNpF:brn83i5) ([raw file](https://github.com/gaelcolas/sampler/blob/84af7e13c4d82cff008cdb67824384e622269125/.build/tasks/Invoke-Pester.pester.build.ps1#L81)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

I've changed the name of the variable/parameter from the function, to make it clearer which one is taking precedence. So I think this is correct.
</blockquote></details>

Must have looked in the wrong place when I reviewed last time. :/ Looks good.
___
*[Sampler/Public/Add-Sample.ps1, line 3 at r2](https://reviewable.io/reviews/gaelcolas/sampler/238#-MVAj6FGCegK3utGFNa7:-MVAj6FH8ddQ46r-7E0A:brg1laa) ([raw file](https://github.com/gaelcolas/sampler/blob/80d167a1e96fadcdafd53dc92aa0e36f7879853c/Sampler/Public/Add-Sample.ps1#L3)):*
> ```
> Adding code elements 
> ```

Non-blocking. Indentation was removed here. If it should follow the DSC style guideline we should keep it as it were.

Throughout all split up functions, but can be done later.

**Pull request merged**
