### PR TITLE
Support ModuleFast

### PR DESCRIPTION
**Pull request by johlju**
# Pull Request

### Added
- Support [ModuleFast](https://github.com/JustinGrote/ModuleFast) when
  restoring dependencies by adding the parameter `UseModuleFast` to the
  `build.ps1`, e.g. `./build.ps1 -Tasks noop -ResolveDependency -UseModuleFast`.
  Using ModuleFast will resolve dependencies much faster.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [x] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/437)

### CODE REVIEW

**Comment by gaelcolas** [comment]
Great idea @johlju thanks!
I thin I remember that part of Module fast solution is not using the gallery and instead Justin has some cloudfare shenanigans.
It's great for us but maybe not so great for corps environment so we should check and make sure it's documented.

It's a long PR and don't have the time right now, but is it possible to use ResolveDependency.psd1 to set that -UseModuleFast parameter "by default" for the project?

**Comment by johlju** [comment]
Yes, modules are cached in Cloudflare. 

I suggest that ModuleFast shouldn’t be made default in Sampler since there are bugs/restrictions on using ModuleFast. I cannot seem to save individual prerelease modules, and it doesn’t support module versions that are not using semantic versioning (e.g 2.1.0.0). Justin also mentioned it could be breaking changes so we shouldn’t have this as default for that reason too. 

I’m not sure it is possible to use default parameters for scripts (never tried). But a user could just change the pipelines to include `UseModuleFast` to pass to `build.ps1`, and pass the parameter in command line. 

I had a thought it would be controlled by build.yaml but that is not read in until after dependency has been resolved. Thought it be to big of a change to implement that. 

I mostly saw ModuleFast as a time saver during the development process and not that much of a time saver for the CI/CD pipeline. 

I suggest we have it opt-in for now and when ModuleFast is more stable we can make it default.

**Comment by johlju** [comment]
It is possible to set the default value using - then it will be picked up by the script even if there are no advanced commands in the scripts.

```
$PSDefaultParameterValues = @{'*:UseModuleFast' = $true}
```

**Comment by johlju** [comment]
@gaelcolas when you review, remove whitespace changes and the PR won't be that big. A lot of code are not needed when using ModuleFast so they are wrapped in if-blocks so there are a lot of indentations.

**Comment by johlju** [comment]
I forgot that we can use `Resolve-Dependency.psd1` to set config values! I will update this PR so that it is possible to toggle ModuleFast on or off by config (and overridden by parameter).

**Review by johlju — COMMENTED** [review]
Ready to be reviewed. Updated to support a config value.

> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/437#-:-Nd4MaVHBqAQaLKxk0Nt:b-1aithu)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @gaelcolas)

___
*[`Resolve-Dependency.ps1` line 121 at r2](https://reviewable.io/reviews/gaelcolas/Sampler/437#-Nd4MAAm1uE4Wztnh87R:-Nd4MAAm1uE4Wztnh87S:b-frw23c) ([raw file](https://github.com/gaelcolas/Sampler/blob/a14049c5241e75f52270d292c026d67dac173a92/Resolve-Dependency.ps1#L121)):*
> ```PowerShell
>             it loads an old version if available (or fail to load latest).
>         #>
>         Get-Module -ListAvailable PackageManagement |
> ```

To reviewer: This code was moved further down, line 212. This was to avoid PackageManagement to be imported when it is not necessary.
___
*[`Sampler/Templates/Build/Resolve-Dependency.ps1` line 122 at r6](https://reviewable.io/reviews/gaelcolas/Sampler/437#-Nd4R1kG39KGc3c-HDWz:-Nd4R1kH0gmJRgm0M1Bg:b-frw23c) ([raw file](https://github.com/gaelcolas/Sampler/blob/a14049c5241e75f52270d292c026d67dac173a92/Sampler/Templates/Build/Resolve-Dependency.ps1#L122)):*
> ```PowerShell
>         #>
>         Get-Module -ListAvailable PackageManagement |
>             Where-Object -Property 'ModuleBase' -NotMatch 'powershell.7' |
> ```

To reviewer: This code was moved further down, line 212. This was to avoid PackageManagement to be imported when it is not necessary.

**Comment by gaelcolas** [comment]
I've got some time lined up this (long) weekend to look at this.

**Comment by johlju** [comment]
Awesome! I will be ready to rebase (or make changes if that is required) 😃

**Review by gaelcolas — APPROVED** [review]
Looks good.
I feel there's more that can be done around how we read the RequiredModules psd1 when making the plan to ModuleFast, but that's already great!

**Pull request merged**
