### PR TITLE
Move task Convert_Pester_Coverage

### PR DESCRIPTION
**Pull request by johlju**
# Pull Request

### Fixed

- Renamed task file from `Merge-CodeCoverageFiles.pester.build.ps1` to `JaCoCo.coverage.build.ps1`.
- Move task _Convert_Pester_Coverage_ to task file `JaCoCo.coverage.build.ps1`.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/272)

### CODE REVIEW

**Comment by johlju** [comment]
@gaelcolas first step in fixing the task. Make small changes in a number of PRs that are quick to review.

**Review by gaelcolas — APPROVED** [review]
Is the filename right?
All good besides that

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/272#-:-MY9GPZ09HPmZ4jwdsb2:bcz93d0)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[CHANGELOG.md, line 12 at r2](https://reviewable.io/reviews/gaelcolas/sampler/272#-MY9FZmn2xS8KRQVyvHM:-MY9FZmn2xS8KRQVyvHN:bhnnc3s) ([raw file](https://github.com/gaelcolas/sampler/blob/b27613ad4efa58c4887deca575bf2bf184728573/CHANGELOG.md#L12)):*
> ```Markdown
> ### Fixed
> 
> - Renamed task file from `Merge-CodeCoverageFiles.pester.build.ps1` to `JaCoCo..coverage.build.ps1`.
> ```

extra . ? JaCoCo..co is that intentional?

**Comment by johlju** [comment]
The extra ‘.’ should not be there. Thought I got rid of it everywhere. Will double check everything again 😃 Good catch!

**Comment by johlju** [comment]
I must remember to use my reading glasses when coding on high DPI screens like Surface Book. 😆

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/272)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @gaelcolas)

___
*[CHANGELOG.md, line 12 at r2](https://reviewable.io/reviews/gaelcolas/sampler/272#-MY9FZmn2xS8KRQVyvHM:-MY9MfcJ7LDzsAWQXarS:bs7wumx) ([raw file](https://github.com/gaelcolas/sampler/blob/b27613ad4efa58c4887deca575bf2bf184728573/CHANGELOG.md#L12)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

extra . ? JaCoCo..co is that intentional?
</blockquote></details>

Done.

**Comment by johlju** [comment]
Merging this when the tests passes.

**Pull request merged**
