### PR TITLE
Fix shallow fetch depth in pipeline

### LINKED ISSUE #424: New Azure Pipelines does shallow fetch by default
### Problem description

New Azure Pipelines do shallow fetch by default which make GitVersion to fail since all commit history is not available.

### Verbose logs

```text
Not available
```

### How to reproduce

Run the current pipeline in a newly created Azure Pipelines pipeline.

### Expected behavior

Should not do shallow fetch.

### Current behavior

Does shallow fetch.

### Suggested solution

Add the following to [azure-pipelines.yml](https://github.com/gaelcolas/Sampler/blob/main/azure-pipelines.yml):

```yaml
variables:
  Agent.Source.Git.ShallowFetchDepth: 0
```

### Operating system the target node is running

```text
n/a
```

### PowerShell version and build the target node is running

```text
n/a
```

### Module version used

```text
n/a
```

### PR DESCRIPTION
**Pull request by fslef**
# Pull Request

New Azure Pipelines do shallow fetch by default which make GitVersion to fail since all commit history is not available.

### Fixed
- `azure-pipelines.yml`
  - Fixes #424 

## Task list

- [ ] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [ ] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [ ] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/425)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/425)* status: all files reviewed, 1 unresolved discussion (waiting on @fslef)

*[a discussion](https://reviewable.io/reviews/gaelcolas/Sampler/425#-NTEsdKXAm7tZ90iMcDN:-NTEsdKYCDiNyLPgcRwP:b-1fjggy) (no related file):*
Please add the same to the template files

- https://github.com/gaelcolas/Sampler/blob/main/Sampler/Templates/Sampler/azure-pipelines.yml.template
- https://github.com/gaelcolas/Sampler/blob/main/Sampler/Templates/Sampler/azure-pipelines_dsccommunity.yml.template

___

**Comment by johlju** [comment]
@fslef thank you for fixing this. We just need the change in the Plaster template files too. See comment. 🙂

**Review by johlju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/425)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fslef)

**Comment by johlju** [comment]
@fslef thank you 🙇‍♂️

**Comment by fslef** [comment]
Your're welcome. My pleasure to contribute.

**Pull request merged**
