### PR TITLE
Task `Set_PSModulePath`: Expanding `PSModulePath`

### PR DESCRIPTION
**Pull request by raandree**
# Pull Request

## Pull Request (PR) description

So far the `PSModulePath` configured in the `build.yml` was a static value. Do make it more flexible, the `PSModulePath` is not expanded.

```yaml
SetPSModulePath:
  PSModulePath: $([System.Environment]::GetFolderPath('MyDocuments'))\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;c:\Users\Install\.vscode\extensions\ms-vscode.powershell-2022.5.1\modules;
  #RemovePersonal: false
  #RemoveProgramFiles: false
  #RemoveWindows: false
```

### Changed
- Set_PSModulePath: The PSModulePath is now expanded and can therefore also
  contain variables.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/463)

### CODE REVIEW

**Comment by raandree** [comment]
@johlju, @gaelcolas, do you have any idea why this isn't working. When building on a Windows Server 2022 build agent, it runs fine.

**Comment by johlju** [comment]
It uses PSResurceGet now in the pipeline. Maybe something changed on the build workers so it started to fail now. I will dig into it this weekend. For now you can switch off PSResurceGet by setting it to false in Resolve-Dependecies.psd1. Hopefully the build passes then.

**Comment by raandree** [comment]
Thanks, @johlju. But, when following your advice and disabling `PSResourceGet` in a PR, we would disable it for the main branch as well. I guess this is not what you want, right?

**Comment by johlju** [comment]
If this is a problem with PSResourceGet then I think we need to turn it off temporarily until I can investigate why it's happening. But please first try to enable the use of the compatibility module in the Resolve-Dependency.psd1 if it is not already enabled. 

I think build workers was updated to PS 7.4.1 recently. PSResourceGet was included in that apparently. So maybe there is an issue with the PowerShellGet compatibility module not being included in PS 7.4.1 or download as part of the pipeline (there is a setting for that too), or a bug in the PowerShellGet compatibility module. We might need to refactor all tasks that use PowerShellGet commands to instead use PSResourceGet commands when available. Then we don't rely on the compatibility module.

**Comment by johlju** [comment]
> But please first try to enable the use of the compatibility module in the Resolve-Dependency.psd1 if it is not already enabled. 

It was already enabled, so there is an issue sonewhere. So suggest temporarily turning off PSResourceGet until we can investigate. So we get this PR through. 😊

**Comment by johlju** [comment]
It seems to be an issue with the image `ubuntu-latest`. Not sure what, switching to `windows-latest` made it start working. Will switch to `windows-latest` to fix the issue for now.

**Comment by johlju** [comment]
@raandree build works now, but integration tests are failing due to this change

**Comment by raandree** [comment]
I have merged the latest changed but the build is failing again with errors that are not related to my change. Is the build working at all at the moment?

**Comment by johlju** [comment]
I have fixed the test pipeline. It seems there were changes on the build worker that affected the tests. If you rebase again that error should not happen now.

**Comment by johlju** [comment]
@raandree I resolved the conflicts so it would pull in latest changes. Now the build fails due to the suggested changes. Looks like Plaster does not like the variable in the template. 🤔

**Comment by raandree** [comment]
@johlju, I have tried to get it working but Plaster cannot handle subexpressions. I have removed them and added a comment. Does that work?

**Comment by johlju** [comment]
It works if we document how to use it here: https://github.com/gaelcolas/Sampler/blob/main/README.md#set_psmodulepath

**Comment by raandree** [comment]
Sure @johlju, the documentation has been updated.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/463#-:-O5EfQE83OvBu0eXCZvv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @raandree)

**Pull request merged**
