### PR TITLE
Template - VSCode: Add extensions.json

### PR DESCRIPTION
**Pull request by dan-hughes**
# Pull Request

## Pull Request (PR) description
Add extensions.json to add recommended extensions.

### Added
- Added extensions.json for vscode

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/469)

### CODE REVIEW

**Comment by dan-hughes** [comment]
@johlju, as per ActiveDirectoryDSC.

Just a note, I could only get this to build using PS7. 5.1 failed with a file encoding issue with ```Sampler.psd1``` having a BOM.

**Comment by johlju** [comment]
> 5.1 failed with a file encoding issue with Sampler.psd1 having a BOM.

No file should have BOM. Do you mean the file in the repo is _UTF with BOM_, because I can't see it? 🤔

**Comment by johlju** [comment]
> I didn't know if I needed to bump the version in the plasterManifest.

I have never done that, didn't even know there were a version in there 😃

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/469)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

*[a discussion](https://reviewable.io/reviews/gaelcolas/Sampler/469#-NvbhgnkADB2Owu4bHj2:-NvbhgnkADB2Owu4bHj3:b-qbo536) (no related file):*
I think we also need to add the new file here:

https://github.com/gaelcolas/Sampler/blob/5b43dd82d81a541d32c4aab17cd7486557d89b69/Sampler/Templates/Sampler/plasterManifest.xml#L658-L674

___

**Comment by johlju** [comment]
Ah, never checked the output directory when running 5.1 honestly so that has probably gone by unnoticed. Let's ignore that for now. 😊

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/469#-:-NvgsmsZ2D3-l-Ccv7tN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

**Pull request merged**
