### PR TITLE
Add ModuleBuilder pattern code coverage support

### PR DESCRIPTION
**Pull request by johlju**
# Pull Request

### Added
- Support for code coverage when using ModuleBuilder pattern for building module.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/263)

### CODE REVIEW

**Comment by johlju** [comment]
There is a problem with `Update-JaCoCoStatistic` that I haven't dug into yet. It doesn't update the statistics correctly. I just want to see if this will upload to Codecov.io at all. 🙂

**Comment by johlju** [comment]
It seems that `Merge-JaCoCoReport` doesn't do right against the DTD, so it fails check.

For example it must add nodes in the correct order, must add the `report` element's counters after the last `package` element.

```
<report name="Pester (04/03/2021 18:20:03)">
  <sessioninfo id="this" start="1617473772414" dump="1617474003894" />
  <package name="0.110.0">
  ...
  </package>
  <counter type="INSTRUCTION" missed="481" covered="65" />
  <counter type="LINE" missed="373" covered="58" />
  <counter type="METHOD" missed="21" covered="3" />
  <counter type="CLASS" missed="1" covered="0" />
</report>

**Comment by johlju** [comment]
I see I have to convert backslash to forward slash as well.

**Comment by johlju** [comment]
There seems there is a bug in `Merge-JaCoCoReport` as well. For each package that does not already exist it adds the entire merge document, which means there are many duplicate `package` elements.

**Comment by johlju** [comment]
Testing the upload to Codecov.io here and it seem to work: https://github.com/dsccommunity/DscResource.DocGenerator/pull/70

Would be great to merge this PR so I can continue testing. It should not affect any repo since one have to add the new task.

@ykuijs can you review  the changes to *JaCoCo* functions so they does not affect SharePointDsc in a negative way?

**Comment by johlju** [comment]
@gaelcolas if it would be possible I like to merge this build task and then come back later and split it up into functions to reduce the length of the function/task in another PR.

**Comment by gaelcolas** [comment]
Yeah sure. let me have a look tomorrow (tentatively).

**Comment by johlju** [comment]
Great! 

Added one more commit - I saw it failed on Windows PowerShell due to it handles (not) loading of DTD differently (looks like more of a bug in `[System.Xml.XmlDocument]`). This does not happen in PowerShell

**Comment by johlju** [comment]
I added a few tiny fixes to comments.

**Review by gaelcolas — APPROVED** [review]
Amazing! Can't wait to use it!

**Pull request merged**
