### PR TITLE
Fix wrong resource name is added in manifest #220

### PR DESCRIPTION
**Pull request by NicolasBn**
# Pull Request

## Pull Request (PR) description

The task searchs the schema.mof file in DSCResource folder and search the friendlyName in MOF File with regex. 
If no friendlyname found, the task uses the BaseName of DSCResource Folder. 

### Fixed

- Wrong resource name is added to module manifest property DscResourcesToExport #220

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/221)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/221)* status: all files reviewed, 1 unresolved discussion (waiting on @NicolasBn)

___
*[.build/tasks/Common.Functions.psm1, line 744 at r1](https://reviewable.io/reviews/gaelcolas/sampler/221#-MOXRZSfC_g6068A8k-V:-MOXRZSfC_g6068A8k-W:b-ufuvsu) ([raw file](https://github.com/gaelcolas/sampler/blob/3975ff71a2776909c3620b7e3dd2dcada5205a77/.build/tasks/Common.Functions.psm1#L744)):*
> ```
> $mofContent = Get-Content -Path $FilePath -TotalCount 1
> ```

The line we want is not necessarily on line 1 if there are blank rows before, or other comment sections above (not sure if it is allowed)

Would it be better to parse it using similar to this https://github.com/dsccommunity/DscResource.DocGenerator/blob/master/source/Private/Get-MofSchemaObject.ps1

**Comment by NicolasBn** [comment]
This is what I failed to find ! Thank you ! 
I will change my code asap.

**Comment by NicolasBn** [comment]
I looked at in detail your function. I saw that there is a restriction of using the type [Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache] on MacOS. 

This implies that sampler cannot be used on MacOS to develop DSC resources.
I wonder. Is it not more simple to use Select-String to just extract the FriendlyName of the resource without dependencies of the OS ?

**Comment by johlju** [comment]
There are more issues with macOS a with MOF resources. Those developing on macOS knows the limitations, like me. 
I think we can use the function, but we should make sure the build task does not stop before it created the module in the output folder. So instead of throwing we should write a warning that the schema could not be read. The module manifest property is not important for the development of MOF resources on macOS. It is just important in the pipeline and that uses Linux. 

@gaelcolas do you have input here. What direction would you like to go?

**Comment by gaelcolas** [comment]
Hmmmm, given the PS Team is making way to get rid of `Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache` (in the move to support only Class Based DSC Resources in 7.x), either we do both with if/then, or we just go to regex (as long as it's solid)...
What do you think?

**Comment by gaelcolas** [comment]
(by that I mean they will get rid of CIM/MOF, so won't parse MOF anymore).
So I'm not sure is the answer :)

**Comment by NicolasBn** [comment]
The regex is good for me. 
I just need different exemples of mof syntax to make the most robust regex.

**Comment by johlju** [comment]
I suggest we decide to use the `Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache` even if that has an issue on macOS. I think this is the fastest route and is most stable for the pipeline. 

Since the goal is to remove mof resources this will not be an issue for macOS in the long run. This code we add now will only be used during the transition from mof to class based.

**Comment by johlju** [comment]
@NicolasBn @gaelcolas 👆

**Comment by gaelcolas** [comment]
Agreed with @johlju actually.
Long run MOF issue won't be as MOF resources are phased out.
Let's just make sure the task is not stopping if `Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache` is not found.

**Comment by NicolasBn** [comment]
I adapted the function to accept entries by pipeline. In this way, only one temp file is created. 
@johlju @gaelcolas

**Review by johlju — CHANGES_REQUESTED** [review]
Great work @nicolasbn. Just a few minor style comments to align the new code with the rest.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/221#-:-MPhsjrJELsxlAtnpQqD:bfukuxk)* status: all files reviewed, 9 unresolved discussions (waiting on @NicolasBn)

___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 406 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhqP-CCfpC5-y2GzOh:-MPhqP-CCfpC5-y2GzOi:b-zhirby) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L406)):*
> ```
> -include
> ```

We should use upper-case `I` in `Invlude`
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 410 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhqWnK7Ww8xviHciEJ:-MPhqWnK7Ww8xviHciEK:b-mvqg3x) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L410)):*
> ```
> Foreach-Object {
> ```

We should use named parameters `ForEach-Object -Process`. Also upper-case 'E' in `ForEach-Object`.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 411 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhqq6yArNt6yTa9IGq:-MPhqq6yArNt6yTa9IGr:b-cjkh4) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L411)):*
> ```
> [system.string]
> ```

We should use `[System.String]` (upper-case 'S') to align with the other code.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 423 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhq9Lq40Wg6kC5lGmM:-MPhq9Lq40Wg6kC5lGmN:bd5156g) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L423)):*
> ```
> Write-Warning (
> ```

We should use named parameters `Write-Warning -Message`
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 428 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhrG7m7HQv0b3RE8KI:-MPhrG7m7HQv0b3RE8KJ:bbfhm2l) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L428)):*
> ```
> Write-Warning (
> ```

We should use named parameters `Write-Warning -Message`. There is also no need for parenthesis. 
___
*[.build/tasks/Common.Functions.psm1, line 745 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhr_CB-6mbyb-25Osv:-MPhr_CB-6mbyb-25Osw:b-rp7q6x) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L745)):*
> ```PowerShell
>         $FilePath
>     )
>     begin {
> ```

Can we add a new line before `begin`.
___
*[.build/tasks/Common.Functions.psm1, line 745 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhrcYm16-VZQUNyAc4:-MPhrcYm16-VZQUNyAc5:b6ay2hg) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L745)):*
> ```
> begin {
> ```

Can we move the open brace to its own row? Aligns with the other code.
___
*[.build/tasks/Common.Functions.psm1, line 779 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhrh5kAcOPEHV_ueCt:-MPhrh5kAcOPEHV_ueCu:b-ubp2h2) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L779)):*
> ```
> process {
> ```

Can we move the open brace to its own row?  Aligns with the other code.
___
*[.build/tasks/Common.Functions.psm1, line 809 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhrxEXDYmhP-DKJcMa:-MPhrxEXDYmhP-DKJcMb:bz2f8qf) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L809)):*
> ```
> Where-Object Name -eq FriendlyName
> ```

We should use named parameters `Where-Object -FilterScript { $_.Name -eq 'FriendlyName' }`, or `Where-Object -Property 'Name' -EQ -Value 'FriendlyName'`. Also we can explicit show that it is strings by surrounding them with `'`.

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/221)* status: all files reviewed, 11 unresolved discussions (waiting on @NicolasBn)

___
*[.build/tasks/Common.Functions.psm1, line 801 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPht8IJ53RtQ7MVG1DM:-MPht8IJ53RtQ7MVG1DN:b-atvri2) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L801)):*
> ```
> Remove-Item -LiteralPath $tempFilePath -Force
> ```

We need to have this row before the `throw. 
___
*[.build/tasks/Common.Functions.psm1, line 804 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhtpQ31pdnYyw2-x7d:-MPhtpQ31pdnYyw2-x7e:b-hhtqfg) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L804)):*
> ```
> Set-Content -LiteralPath $tempFilePath -Value ''
> ```

What are your thoughts about doing this, can we not just remove the file in a `finally`-block instead? Then it will be removed regardless of the outcome of the try-block. We wouldn't need to remove the file in the `end`-block below either?

**Review by NicolasBn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/221)* status: all files reviewed, 11 unresolved discussions (waiting on @johlju)

___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 406 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhqP-CCfpC5-y2GzOh:-MPhy0OAEaeH__Pky1H0:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L406)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> -include
> ```

We should use upper-case `I` in `Invlude`
</blockquote></details>

Done.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 410 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhqWnK7Ww8xviHciEJ:-MPhxqd177Z_ADrl5hHa:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L410)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Foreach-Object {
> ```

We should use named parameters `ForEach-Object -Process`. Also upper-case 'E' in `ForEach-Object`.
</blockquote></details>

Done.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 411 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhqq6yArNt6yTa9IGq:-MPhxjh3E0DLchLES0qR:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L411)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [system.string]
> ```

We should use `[System.String]` (upper-case 'S') to align with the other code.
</blockquote></details>

Done.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 423 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhq9Lq40Wg6kC5lGmM:-MPhy-oRCR8MM00vQhA5:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L423)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Write-Warning (
> ```

We should use named parameters `Write-Warning -Message`
</blockquote></details>

Done.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 428 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhrG7m7HQv0b3RE8KI:-MPhxjGC7Pk2MbiAgVBj:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L428)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Write-Warning (
> ```

We should use named parameters `Write-Warning -Message`. There is also no need for parenthesis. 
</blockquote></details>

Done.
___
*[.build/tasks/Common.Functions.psm1, line 745 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhr_CB-6mbyb-25Osv:-MPhwfNr2rm_U3KY9lvu:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L745)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we add a new line before `begin`.
</blockquote></details>

Done.
___
*[.build/tasks/Common.Functions.psm1, line 745 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhrcYm16-VZQUNyAc4:-MPhwuKu6EgtBUHkKQBG:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L745)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> begin {
> ```

Can we move the open brace to its own row? Aligns with the other code.
</blockquote></details>

Done.
___
*[.build/tasks/Common.Functions.psm1, line 779 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhrh5kAcOPEHV_ueCt:-MPhwzDl1khFfuhe1-SZ:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L779)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> process {
> ```

Can we move the open brace to its own row?  Aligns with the other code.
</blockquote></details>

Done.
___
*[.build/tasks/Common.Functions.psm1, line 801 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPht8IJ53RtQ7MVG1DM:-MPhxW1e0VwUQvh1jmpa:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L801)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Remove-Item -LiteralPath $tempFilePath -Force
> ```

We need to have this row before the `throw. 
</blockquote></details>

Done.
___
*[.build/tasks/Common.Functions.psm1, line 804 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhtpQ31pdnYyw2-x7d:-MPhvjYu5B_2JCF2OHiA:b-zi36gh) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L804)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Set-Content -LiteralPath $tempFilePath -Value ''
> ```

What are your thoughts about doing this, can we not just remove the file in a `finally`-block instead? Then it will be removed regardless of the outcome of the try-block. We wouldn't need to remove the file in the `end`-block below either?
</blockquote></details>

I thought that it will be most efficiency if we re-use the same temp file. But if I'm wrong, I can correct it.
___
*[.build/tasks/Common.Functions.psm1, line 809 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhrxEXDYmhP-DKJcMa:-MPhyJXbDNNgSoAFC-XB:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L809)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Where-Object Name -eq FriendlyName
> ```

We should use named parameters `Where-Object -FilterScript { $_.Name -eq 'FriendlyName' }`, or `Where-Object -Property 'Name' -EQ -Value 'FriendlyName'`. Also we can explicit show that it is strings by surrounding them with `'`.
</blockquote></details>

Done.

**Review by johlju — CHANGES_REQUESTED** [review]
Just a few more tweaks then this is done I think! :smiley: 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/221#-:-MPi3C1T3rwDwBD6-8g7:b6ro05e)* status: all files reviewed, 4 unresolved discussions (waiting on @NicolasBn)

___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 410 at r4](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPi2LKgCTi-J5tJzfVE:-MPi2LKgCTi-J5tJzfVF:b-h4t03q) ([raw file](https://github.com/gaelcolas/sampler/blob/684adea079b0382cd7cd5af00c1ef07952452540/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L410)):*
> ```
> ForEach-Object  -Process
> ```

There is a n extra space before `-Process`. Can we remove one?
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 428 at r4](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPi2TiaDfC-AuDx7ApC:-MPi2TiaDfC-AuDx7ApD:b-xtutdj) ([raw file](https://github.com/gaelcolas/sampler/blob/684adea079b0382cd7cd5af00c1ef07952452540/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L428)):*
> ```
> folder '
> ```

Can we remove the space after the word 'folder'?
___
*[.build/tasks/Common.Functions.psm1, line 745 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhr_CB-6mbyb-25Osv:-MPi2_tR0WTig01LdgUc:b982daz) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L745)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not seeing the new line before `begin`, can we add it?
___
*[.build/tasks/Common.Functions.psm1, line 804 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhtpQ31pdnYyw2-x7d:-MPi2mR4CAx4HS36z6He:bxfhtct) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L804)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

I thought that it will be most efficiency if we re-use the same temp file. But if I'm wrong, I can correct it.
</blockquote></details>

Ah, I see, works for me. Can you phrase that in  a comment so we remember why this is done?

**Review by NicolasBn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/221)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 410 at r4](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPi2LKgCTi-J5tJzfVE:-MPi5vF73LxHZQV63L5b:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/684adea079b0382cd7cd5af00c1ef07952452540/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L410)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ForEach-Object  -Process
> ```

There is a n extra space before `-Process`. Can we remove one?
</blockquote></details>

Done.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 428 at r4](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPi2TiaDfC-AuDx7ApC:-MPi5w3E9Hou2zkVaHsr:b6sej96) ([raw file](https://github.com/gaelcolas/sampler/blob/684adea079b0382cd7cd5af00c1ef07952452540/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L428)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> folder '
> ```

Can we remove the space after the word 'folder'?
</blockquote></details>

Done. sorry for my frenetic click on the space barre :)
___
*[.build/tasks/Common.Functions.psm1, line 745 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhr_CB-6mbyb-25Osv:-MPi5ywJ95ioby5wEO_A:bchgjxt) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L745)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not seeing the new line before `begin`, can we add it?
</blockquote></details>

I missed it ! Sorry, I corrected it. 
___
*[.build/tasks/Common.Functions.psm1, line 804 at r3](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPhtpQ31pdnYyw2-x7d:-MPi63cwBY_c_IeMJAT8:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/c7cdddafbcc8f7ade813c08f53508b583848bcb8/.build/tasks/Common.Functions.psm1#L804)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Ah, I see, works for me. Can you phrase that in  a comment so we remember why this is done? 
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/221#-:-MPiMG5qDigxPVRuW9S9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NicolasBn)

___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 428 at r4](https://reviewable.io/reviews/gaelcolas/sampler/221#-MPi2TiaDfC-AuDx7ApC:-MPiM6msAEvPZ9Fk-yQY:bja5b4k) ([raw file](https://github.com/gaelcolas/sampler/blob/684adea079b0382cd7cd5af00c1ef07952452540/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L428)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

Done. sorry for my frenetic click on the space barre :)
</blockquote></details>

Haha no worries. :wink:

**Comment by johlju** [comment]
@NicolasBn awesome work on this! I push a new release as soon the test passes. 😃

**Pull request merged**
