### PR TITLE
adding a class based DSC resource template

### PR DESCRIPTION
**Pull request by gaelcolas**
# Pull Request

In an effort to make adding components a little bit easier, I'm creating some templates.
The idea is to make it easier to create elements that are already compliant with code styles, build and all...

I've added a Class based resource, and I'll be adding a composite next.

I've also renamed enums to enum because other it does not merge them with ModuleBuilder: https://github.com/PoshCode/ModuleBuilder/blob/master/Source/Public/Build-Module.ps1#L93

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/185)

### CODE REVIEW

**Review by gaelcolas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/185)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF1Ub3Y2iYyctlpd2Ke:-MF3C6Bp9U0A1rrqpzDL:b4tdwc) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can you add integration tests for the new templates?
</blockquote></details>

Yeah, will do before marking as ready for review.
For now I've added templates for DSC composite and Class based.
It's minimum info (those template should also add tests associated with them, optionally), but at least it makes it an easy quick start.
Feel free to let me know if I should add things, and I'm thinking on moving the DSC resource & sample functions in the same way.

---

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/185)* status: all files reviewed, 5 unresolved discussions (waiting on @gaelcolas)

___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 134 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5SAT44LFsKQnVwd8n:-MF5SAT44LFsKQnVwd8o:bnd3qw2) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L134)):*
> ```
> Get-Content -Raw $Psm1Path
> ```

Should use named parameters `Get-Content -Path $Psm1Path -Raw`
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 164 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5QHLF07cIYpO7TL5j:-MF5QHLF07cIYpO7TL5k:b6bistu) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L164)):*
> ```
> !
> ```

We should use `-not` instead of `!` to increase the readability and I comment mostly becuase that is way we do for DSC HQRM. ;) Non-blocking.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 164 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5ROUa6lKWfkJVamPz:-MF5ROUa6lKWfkJVamQ-:b-co5u7d) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L164)):*
> ```
> (Get-Command -name Import-PowerShellDataFile -ErrorAction SilentlyContinue)
> ```

I (and I know Daniel a swell) rather see that we do these outside if the if-block to make the if-block just do one thing.. 

```
$isImportPowerShellDataFileAvailable = Get-Command -name Import-PowerShellDataFile -ErrorAction SilentlyContinue

if ($PSversionTable.PSversion.Major -le 5 -and -not $isImportPowerShellDataFileAvailable)
```
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 164 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5RxHjAGDkFyntbWsZ:-MF5RxHk5hDQ0beCVc2p:bmryy95) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L164)):*
> ```
> -name
> ```

`-Name` (upper-case  `N`)
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 166 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5R2EC6BcdRGamnqSe:-MF5R2EC6BcdRGamnqSf:b-h9stfj) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L166)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> if ($PSversionTable.PSversion.Major -le 5 -and !(Get-Command -name Import-PowerShellDataFile -ErrorAction SilentlyContinue))
>     {
>         Import-Module Microsoft.PowerShell.Utility -RequiredVersion 3.1.0.0
>     }
> ```
</details>


If we need to do this in several tasks/helper functions then we should make this code a helper function as well.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 166 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5S0vX83xCtAZ9aPUH:-MF5S0vX83xCtAZ9aPUI:b-gcxnw2) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L166)):*
> ```
> Import-Module Microsoft.PowerShell.Utility
> ```

Should use named parameter `-Name`.
___
*[.build/tasks/Invoke-Pester.pester.build.ps1, line 89 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5SS7i2qNYwr-47QZC:-MF5SS7i2qNYwr-47QZD:baceix7) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Invoke-Pester.pester.build.ps1#L89)):*
> ```
> -ErrorVariable PesterErr
> ```

This is never used? What is the reason to set this?

**Comment by johlju** [comment]
@gaelcolas mostly style changes in the task.

**Review by gaelcolas — COMMENTED** [review]
Should be all fixed.

> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/185#-:-MF5qiBn9CjmFYgThrYM:bh7mtu6)* status: 20 of 22 files reviewed, 5 unresolved discussions (waiting on @johlju)

___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 134 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5SAT44LFsKQnVwd8n:-MF5q0q-7rfAruWTkabl:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L134)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Get-Content -Raw $Psm1Path
> ```

Should use named parameters `Get-Content -Path $Psm1Path -Raw`
</blockquote></details>

Done.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 164 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5QHLF07cIYpO7TL5j:-MF5q6C59tCQtEK21cR0:ba27rsu) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L164)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> !
> ```

We should use `-not` instead of `!` to increase the readability and I comment mostly becuase that is way we do for DSC HQRM. ;) Non-blocking.
</blockquote></details>

fixed, old habits die hard...
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 164 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5ROUa6lKWfkJVamPz:-MF5qBEOAoHXwPDn9-7e:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L164)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> (Get-Command -name Import-PowerShellDataFile -ErrorAction SilentlyContinue)
> ```

I (and I know Daniel a swell) rather see that we do these outside if the if-block to make the if-block just do one thing.. 

```
$isImportPowerShellDataFileAvailable = Get-Command -name Import-PowerShellDataFile -ErrorAction SilentlyContinue

if ($PSversionTable.PSversion.Major -le 5 -and -not $isImportPowerShellDataFileAvailable)
```
</blockquote></details>

Done.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 164 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5RxHjAGDkFyntbWsZ:-MF5qBtSAba7Cxi9Fd5s:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L164)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> -name
> ```

`-Name` (upper-case  `N`)
</blockquote></details>

Done.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 166 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5S0vX83xCtAZ9aPUH:-MF5qKqwBkNwpn7mwvb2:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L166)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Import-Module Microsoft.PowerShell.Utility
> ```

Should use named parameter `-Name`.
</blockquote></details>

Done.
___
*[.build/tasks/Build-Module.ModuleBuilder.build.ps1, line 166 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5R2EC6BcdRGamnqSe:-MF5qLIW2ZzCBdtCbxgV:bxd5l1b) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L166)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($PSversionTable.PSversion.Major -le 5 -and !(Get-Command -name Import-PowerShellDataFile -ErrorAction SilentlyContinue))
>     {
>         Import-Module Microsoft.PowerShell.Utility -RequiredVersion 3.1.0.0
>     }
> ```

If we need to do this in several tasks/helper functions then we should make this code a helper function as well.
</blockquote></details>

I think it's only in one task, and otherwise it's before anything else gets loaded (before bootstrap), so we can't rely on any function unfortunately.
___
*[.build/tasks/Invoke-Pester.pester.build.ps1, line 89 at r2](https://reviewable.io/reviews/gaelcolas/sampler/185#-MF5SS7i2qNYwr-47QZC:-MF5qZXc8-0zRzBmaJrj:bmpm82s) ([raw file](https://github.com/gaelcolas/sampler/blob/9c0e6d221d639b70819996ca31bd7ef3158d5bcc/.build/tasks/Invoke-Pester.pester.build.ps1#L89)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> -ErrorVariable PesterErr
> ```

This is never used? What is the reason to set this?
</blockquote></details>

ok. removed, I think I was doing something here I might have removed... Oops.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/185#-:-MF6yh3ZB-KytSqxsthm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
