### PR TITLE
Add task `Pester_Run_Times`

### PR DESCRIPTION
**Pull request by johlju**
# Pull Request

### Added
- New task `Pester_Run_Times` that outputs each test's run time. Only works
  for Pester 5. The task will be skipped if Pester 4 is used.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/363)

### CODE REVIEW

**Comment by johlju** [comment]
The output from this is like this for a repo that uses Pester 5 (in this case SqlServerDsc):

```
===============================================================================
                        PESTER RUN TIMES
List the run time for each Pester test.
-------------------------------------------------------------------------------
  /test/Pester_Tests_Stop_On_Fail/Pester_Run_Times
  C:\source\SqlServerDsc\output\RequiredModules\Sampler\0.112.1\tasks\Invoke-Pester.pester.build.ps1:1069

        Project Name               = 'SqlServerDsc'
        Source Path                = 'C:\source\SqlServerDsc\source'
        Output Directory           = 'C:\source\SqlServerDsc\output'
        Release Notes path         = 'C:\source\SqlServerDsc\output\ReleaseNotes.md'
        Built Module Subdirectory  = 'C:\source\SqlServerDsc\output\'
        Module Manifest Path (src) = 'C:\source\SqlServerDsc\source\SqlServerDsc.psd1'
        Versioned Output Directory = 'True'
        Built Module Manifest      = 'C:\source\SqlServerDsc\output\SqlServerDsc\16.0.0\SqlServerDsc.psd1'
        Built Module Base          = 'C:\source\SqlServerDsc\output\SqlServerDsc\16.0.0'
        Module Version             = '16.0.0-support'
        Module Version Folder      = '16.0.0'
        Pre-release Tag            = 'support'
        Built Module Root Script   = ''

        Pester Output Folder     = C:\source\SqlServerDsc\output\testResults
        Pester Output Object     = C:\source\SqlServerDsc\output\testResults\PesterObject_SqlServerDsc_v16.0.0-support.Windows.PSv.7.2.3.xml

Test script file                           Duration
--------------------------------------------------------------------
DSC_SqlAG.Tests.ps1                        0 seconds (NotRun)
DSC_SqlAGDatabase.Tests.ps1                0 seconds (NotRun)
DSC_SqlAgentAlert.Tests.ps1                0 seconds (Passed)
DSC_SqlAgentFailsafe.Tests.ps1             0 seconds (Passed)
DSC_SqlAgentOperator.Tests.ps1             0 seconds (Passed)
DSC_SqlAGListener.Tests.ps1                0 seconds (NotRun)
DSC_SqlAGReplica.Tests.ps1                 0 seconds (NotRun)
DSC_SqlAlias.Tests.ps1                     3 seconds (Passed)
DSC_SqlAlwaysOnService.Tests.ps1           1 seconds (Passed)
DSC_SqlConfiguration.Tests.ps1             0 seconds (Passed)
DSC_SqlDatabase.Tests.ps1                  1 seconds (Passed)
DSC_SqlDatabaseDefaultLocation.Tests.ps1   0 seconds (Passed)
DSC_SqlDatabaseMail.Tests.ps1              1 seconds (Passed)
DSC_SqlDatabaseObjectPermission.Tests.ps1  2 seconds (Passed)
DSC_SqlDatabasePermission.Tests.ps1        0 seconds (Passed)
DSC_SqlDatabaseRole.Tests.ps1              1 seconds (Passed)
DSC_SqlDatabaseUser.Tests.ps1              1 seconds (Passed)
DSC_SqlEndpoint.Tests.ps1                  2 seconds (Passed)
DSC_SqlEndpointPermission.Tests.ps1        0 seconds (Passed)
DSC_SqlLogin.Tests.ps1                     2 seconds (Passed)
DSC_SqlMaxDop.Tests.ps1                    1 seconds (Passed)
DSC_SqlMemory.Tests.ps1                    2 seconds (Passed)
DSC_SqlPermission.Tests.ps1                0 seconds (Passed)
DSC_SqlProtocol.Tests.ps1                  1 seconds (Passed)
DSC_SqlProtocolTcpIp.Tests.ps1             1 seconds (Passed)
DSC_SqlReplication.Tests.ps1               4 seconds (Passed)
DSC_SqlRole.Tests.ps1                      2 seconds (Passed)
DSC_SqlRS.Tests.ps1                        9 seconds (Passed)
DSC_SqlRSSetup.Tests.ps1                   1 seconds (Passed)
DSC_SqlScript.Tests.ps1                    0 seconds (Passed)
DSC_SqlScriptQuery.Tests.ps1               0 seconds (Passed)
DSC_SqlSecureConnection.Tests.ps1          1 seconds (Passed)
DSC_SqlServiceAccount.Tests.ps1            1 seconds (Passed)
DSC_SqlSetup.Tests.ps1                     1 minutes 55 seconds (Passed)
DSC_SqlTraceFlag.Tests.ps1                 1 seconds (Passed)
DSC_SqlWaitForAG.Tests.ps1                 0 seconds (Passed)
DSC_SqlWindowsFirewall.Tests.ps1           19 seconds (Passed)
SqlServerDsc.AnalyzerRules.Tests.ps1       1 seconds (Passed)
SqlServerDsc.Common.Tests.ps1              15 seconds (Passed)

Total run time: 3 minutes 27 seconds

Done /test/Pester_Tests_Stop_On_Fail/Pester_Run_Times 00:00:01.2531221
```

**Comment by johlju** [comment]
Updated to be a bit more simple plus added test counts. My goal is to use this task to see potential drift in testing times so that it is easy to see what tests has slowed (in minutes, not seconds). 🙂

**Comment by johlju** [comment]
Tests will be added in an another PR eventually. Will get this repo's existing test to Pester 5 first (in separate future PR).

**Review by gaelcolas — COMMENTED** [review]
@johlju could you rebase?
I had reviewed it but looks like my review did not submit (was on spotty connection).

> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/363#-:-N1xn08F1ABDwvAkQS5Y:b7eqp3u)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @PlagueHO)

**Comment by johlju** [comment]
I fixed the conflicts, @gaelcolas.

**Review by gaelcolas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/363)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @johlju and @PlagueHO)

___
*[`.build/tasks/Invoke-Pester.pester.build.ps1` line 1128 at r3](https://reviewable.io/reviews/gaelcolas/sampler/363#-N1ySoTfANPhxsUl8FlT:-N1ySoTg0kD52lO1WSCJ:bktldk9) ([raw file](https://github.com/gaelcolas/sampler/blob/23999d57711e621762b89cd4e34f5f168617c9d5/.build/tasks/Invoke-Pester.pester.build.ps1#L1128)):*
> ```PowerShell
>                     Skipped = $_.SkippedCount
>                     Total = $_.TotalCount
> ```

Extra line

**Pull request merged**
