### PR TITLE
Proposition to add DSC_ClassFolder template, an adaptation of DSC_Folder with class

### PR DESCRIPTION
**Pull request by NicolasBn**
# Pull Request

Proposition to add DSC_ClassFolder template to complet a part of issue #108 . 

## Pull Request (PR) description

Proposition to add DSC_ClassFolder template to complete a part of issue #108 . There is no plaster template yet. 
This is just to review my work and change the code to provide a better class based resource. 

I tried to use helpers methods and no helpers functions (like Test-FileAttribute).
It's more difficult to construct pester tests, but I think to have found a way to assert mocking with temporary function :

https://github.com/NicolasBn/Sampler/blob/3072e9b4854870c4549a366eab5fc4272bcd5e0b/Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1#L366

https://github.com/NicolasBn/Sampler/blob/3072e9b4854870c4549a366eab5fc4272bcd5e0b/Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1#L440

### Added
- add DSC_ClassFolder template, an adaptation of DSC_Folder woth class [#108]

## Task list

- [ ] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [X] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [X] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/212)

### CODE REVIEW

**Review by gaelcolas — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/212)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @NicolasBn)

___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 2 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBZnKX9Xxcoc6XXrZ5:-MKBZnKX9Xxcoc6XXrZ6:b-dujgra) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L2)):*
> ```PowerShell
> $script:localizedDataClassFolder = Get-LocalizedData -DefaultUICulture en-US -FileName 'DSC_ClassFolder.strings.psd1'
> ```

Although it makes sense, do we want to have unique localized files for DSC resources, or do we want to have one per module? /cc @johlju @PlagueHO @bielawb @danielboth
I'd prefer one per module so that it's easier to keep consistency between resources.
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 30 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKB_-5g9JGBJBDHLgAv:-MKB_-5g9JGBJBDHLgAw:brepzsj) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L30)):*
> ```PowerShell
>         if ($this.Ensure -eq [Ensure]::Present)
>         {
>             if ($getMethodResourceResult.Ensure -eq 'Absent')
> ```

use [ensure]::Absent instead of 'Absent' 
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 152 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKB_bNT33aZ18B9a4GK:-MKB_bNT33aZ18B9a4GL:bfwt1e0) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L152)):*
> ```PowerShell
>     }
> 
>     [bool] TestFileAttribute (
> ```

I'd argue that this method should be a function Test-FileAttribute (private if possible).
The DSC Resource is only an "interface" to other PowerShell Commands.
Alternatively, the DSC resources could inherit from another PS class that has this method. The point is that it should not be the DSC resource to "add" this functionality.
Same principle applies to MOF resources, we just haven't done it this way yet.
I find it much simpler to maintain and write test for.  
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 172 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBc36E4boFt5JanKaQ:-MKBc36E4boFt5JanKaR:b-imiso1) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L172)):*
> ```PowerShell
>     }
> 
>     [void]SetFileAttribute (
> ```

same (should be a function).
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 193 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBc8vd-voyvx-fZt8S:-MKBc8vd-voyvx-fZt8T:bz4kbq8) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L193)):*
> ```PowerShell
>     }
> 
>     [hashtable] ConvertToHashtable ()
> ```

That should be a function, or rather should use the one from DSCResource.Common
___
*[Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1, line 22 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBcQ8477TimrmKVvHf:-MKBcQ8477TimrmKVvHg:bhguvrf) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1#L22)):*
> ```PowerShell
>         Context 'Constructors' {
>             It 'Has a default constructor' {
>                 $instance = [DSC_ClassFolder]::new()
> ```

does this not throw when there's no empty constructor? (it does not have to be default, it just need to be empty)
___
*[Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1, line 437 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBeETr2Rb1D52hjnSG:-MKBeETr2Rb1D52hjnSH:bligvrj) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1#L437)):*
> ```PowerShell
>                             return $mockinstance
>                         }
>                     #Override SetFileAttribute method with Test-SetFileAttributeMethodUsing function
> ```

ah, one more reason to what I said above.

**Review by NicolasBn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/212)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @bielawb, @danielboth, @gaelcolas, @johlju, and @PlagueHO)

___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 2 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBZnKX9Xxcoc6XXrZ5:-MKER9Z5BlW-Iy0HdL6x:b-ve6s70) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L2)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

Although it makes sense, do we want to have unique localized files for DSC resources, or do we want to have one per module? /cc @johlju @PlagueHO @bielawb @danielboth
I'd prefer one per module so that it's easier to keep consistency between resources.
</blockquote></details>

For LocalizedData, I understand your position. But I think that it is too difficult to manage each unique key in strings.psd1 file for all resources in module.
Or maybe make a standard for key name like this : 
```powershell
ConvertFrom-StringData @'
    <ResourceName>_<ID> = <Message>
'@
```
**Note :** this implies special characters in the keys.
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 30 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKB_-5g9JGBJBDHLgAv:-MKERXlK3dNuVIti2BLg:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L30)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

use [ensure]::Absent instead of 'Absent' 
</blockquote></details>

Done.
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 152 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKB_bNT33aZ18B9a4GK:-MKERiIS-lyq6EHaXmIh:b-7hf8tu) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L152)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

I'd argue that this method should be a function Test-FileAttribute (private if possible).
The DSC Resource is only an "interface" to other PowerShell Commands.
Alternatively, the DSC resources could inherit from another PS class that has this method. The point is that it should not be the DSC resource to "add" this functionality.
Same principle applies to MOF resources, we just haven't done it this way yet.
I find it much simpler to maintain and write test for.  
</blockquote></details>

I see. 
I would experiment the difficulties to make a good test with Pester. 
And i agree : The function is easiest to make a test. 

But I think it's interesting to have method approach. If the Dsc class is based on .net class with method, and there's no function to do the same. 

Can we make two templates ? ClassResource (simple) and ClassResourceAdvanced ?

| Feature | SimpleClass | AdvancedClass |
|--------|--------|--------|
|Get/Set/Test and test | x | x |
| LocalizedData | ? | x |
| Helpers Functions | x | x |
| Parent or .Net Class | | x |
| Reasons | ? | x |
| Pester test advanced | | x |
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 172 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBc36E4boFt5JanKaQ:-MKEV76z38nZb8BQkUDy:b-2dcgv5) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L172)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

same (should be a function).
</blockquote></details>

same too
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 193 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBc8vd-voyvx-fZt8S:-MKEVGyRDMvKpTG5sIJX:b5xpn4u) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L193)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

That should be a function, or rather should use the one from DSCResource.Common
</blockquote></details>

The function in [DSCResource.Common](https://github.com/dsccommunity/DscResource.Common/blob/2032d5a650e00ddee258d377263a599167a27e4f/source/Public/ConvertTo-HashTable.ps1#L6) is limited to Cim object. It's need an update to accept all object.
___
*[Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1, line 22 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBcQ8477TimrmKVvHf:-MKE_0dD21f91l8C9HCj:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1#L22)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

does this not throw when there's no empty constructor? (it does not have to be default, it just need to be empty)
</blockquote></details>

Done.
___
*[Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1, line 437 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBeETr2Rb1D52hjnSG:-MKE_9IkAWVcpjkIeHX0:b-437upk) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1#L437)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

ah, one more reason to what I said above.
</blockquote></details>

See other reply

**Review by gaelcolas — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/212)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @bielawb, @danielboth, @gaelcolas, @johlju, @NicolasBn, and @PlagueHO)

___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 152 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKB_bNT33aZ18B9a4GK:-MKFAo1j0UD31aFJE7VQ:bs7jcvd) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L152)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

I see. 
I would experiment the difficulties to make a good test with Pester. 
And i agree : The function is easiest to make a test. 

But I think it's interesting to have method approach. If the Dsc class is based on .net class with method, and there's no function to do the same. 

Can we make two templates ? ClassResource (simple) and ClassResourceAdvanced ?

| Feature | SimpleClass | AdvancedClass |
|--------|--------|--------|
|Get/Set/Test and test | x | x |
| LocalizedData | ? | x |
| Helpers Functions | x | x |
| Parent or .Net Class | | x |
| Reasons | ? | x |
| Pester test advanced | | x |
</blockquote></details>

Interesting, yes.
Do we want to show this way (extra method) in a template? No.
I assume that people who want to use a method in their DSC class resource despite our advice not to, are skilled enough to not need an advanced template, and most likely do not intend to share the DSC Resource as part of the DSC Community.
Too many resources are not well written because they don't treat DSC resources as a convention to implement idempotency and a resource-oriented approach to configuration management, abstracting away imperative tools.
I'm not against using methods in PS Classes, I'm against doing that in the DSC Class Resources outside of Get/Set/Test.
As for Reasons, they should be everywhere (in samples, at least).
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 193 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBc8vd-voyvx-fZt8S:-MKFADzH0rcHHn9iyDK8:b-nkkmcw) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L193)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

The function in [DSCResource.Common](https://github.com/dsccommunity/DscResource.Common/blob/2032d5a650e00ddee258d377263a599167a27e4f/source/Public/ConvertTo-HashTable.ps1#L6) is limited to Cim object. It's need an update to accept all object.
</blockquote></details>

It can be  new function, ConvertTo-DscHashtableFromPSObject.
The Dsc prefix is to avoid naming conflict with other modules.

**Review by danielboth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/212)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @bielawb, @gaelcolas, @johlju, @NicolasBn, and @PlagueHO)

___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 2 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBZnKX9Xxcoc6XXrZ5:-MKGkopgBaNMpWAujGmR:b-ey2auf) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L2)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

For LocalizedData, I understand your position. But I think that it is too difficult to manage each unique key in strings.psd1 file for all resources in module.
Or maybe make a standard for key name like this : 
```powershell
ConvertFrom-StringData @'
    <ResourceName>_<ID> = <Message>
'@
```
**Note :** this implies special characters in the keys.
</blockquote></details>

I'm wondering, how often do you have the same text (usually for a message, like an error / warning) shared between two or more resources? I can't think of good examples. Maybe in the case where you have some external dependencies that all the resources in the module interact with, but when talking about classes, that is than better implemented using a base class, which then comes with it's own LocalizedData file. How do you feel about that @gaelcolas @nicolasbn ?

**Review by gaelcolas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/212)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @bielawb, @gaelcolas, @johlju, @NicolasBn, and @PlagueHO)

___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 2 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBZnKX9Xxcoc6XXrZ5:-MKGvLug6_gYRzpq0fkj:b4jf031) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L2)):*
<details><summary><i>Previously, danielboth (Daniël) wrote…</i></summary><blockquote>

I'm wondering, how often do you have the same text (usually for a message, like an error / warning) shared between two or more resources? I can't think of good examples. Maybe in the case where you have some external dependencies that all the resources in the module interact with, but when talking about classes, that is than better implemented using a base class, which then comes with it's own LocalizedData file. How do you feel about that @gaelcolas @nicolasbn ?
</blockquote></details>

Fair point.
Happy with one LocalizedData file per resource (or class if appropriate), it will be more maintainable.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/212)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @bielawb, @gaelcolas, @johlju, @NicolasBn, and @PlagueHO)

*[a discussion](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKPBEAA2eVuKNHa6tB1:-MKPBEAA2eVuKNHa6tB2:bh3v96v) (no related file):*
Non-blocking. When this resource is updated and merge we should also plan to add it to the DSC module https://github.com/dsccommunity/FileSystemDsc   

---
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 2 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBZnKX9Xxcoc6XXrZ5:-MKP7r6e8JjleRm1hmQm:btw49q1) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L2)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

Fair point.
Happy with one LocalizedData file per resource (or class if appropriate), it will be more maintainable.
</blockquote></details>

I agree with the conclusion here. I rather see LocalizedData file per DSC resource. Otherwise it would be too big of a chance that a change for one resource wrongly affects another. 
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 152 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKB_bNT33aZ18B9a4GK:-MKP9VTe80znHsbiTWOq:b-d29r43) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L152)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

Interesting, yes.
Do we want to show this way (extra method) in a template? No.
I assume that people who want to use a method in their DSC class resource despite our advice not to, are skilled enough to not need an advanced template, and most likely do not intend to share the DSC Resource as part of the DSC Community.
Too many resources are not well written because they don't treat DSC resources as a convention to implement idempotency and a resource-oriented approach to configuration management, abstracting away imperative tools.
I'm not against using methods in PS Classes, I'm against doing that in the DSC Class Resources outside of Get/Set/Test.
As for Reasons, they should be everywhere (in samples, at least).
</blockquote></details>

I agree this method should not be part of the DSC resource. In a "real world" DSC module there could be more DSC resource that needs this as a private helper function. If a DSC resource should have methods then those should not be public, they should be internal to the DSC resource so there is no chance for users to use the internal helper function. 

This resource should be added to the "real world" DSC module FileSystemDsc (I haven't gotten around to it yet) and in that module there will most likely be more resources that will need several helper functions.

**Review by NicolasBn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/212)* status: 1 of 25 files reviewed, 7 unresolved discussions (waiting on @bielawb, @gaelcolas, @johlju, and @PlagueHO)

___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 2 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBZnKX9Xxcoc6XXrZ5:-MLljne3DyRi0tVBYhIW:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L2)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I agree with the conclusion here. I rather see LocalizedData file per DSC resource. Otherwise it would be too big of a chance that a change for one resource wrongly affects another. 
</blockquote></details>

Done.
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 152 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKB_bNT33aZ18B9a4GK:-MLljrXw5ujta6_j8xns:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L152)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I agree this method should not be part of the DSC resource. In a "real world" DSC module there could be more DSC resource that needs this as a private helper function. If a DSC resource should have methods then those should not be public, they should be internal to the DSC resource so there is no chance for users to use the internal helper function. 

This resource should be added to the "real world" DSC module FileSystemDsc (I haven't gotten around to it yet) and in that module there will most likely be more resources that will need several helper functions. 
</blockquote></details>

Done.
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 172 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBc36E4boFt5JanKaQ:-MLljsfx9zW1XTKabhkU:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L172)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

same too
</blockquote></details>

Done.
___
*[Sampler/Templates/ClassResource/DSC_ClassFolder.ps1, line 193 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBc8vd-voyvx-fZt8S:-MLlk7Vd-JeN1QqEOnVD:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/DSC_ClassFolder.ps1#L193)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

It can be  new function, ConvertTo-DscHashtableFromPSObject.
The Dsc prefix is to avoid naming conflict with other modules.
</blockquote></details>

Done.
___
*[Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1, line 437 at r1](https://reviewable.io/reviews/gaelcolas/sampler/212#-MKBeETr2Rb1D52hjnSG:-MLlkKhe5rZUMBcC1IjC:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/58f1688fcbe1b1f8f4e238666362fce44cc65ff7/Sampler/Templates/ClassResource/tests/Unit/ClassResource/DSC_ClassFolder.tests.ps1#L437)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

See other reply
</blockquote></details>

Done.

**Review by gaelcolas — APPROVED** [review]
> Reviewed 23 of 26 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/212)* status: all files reviewed, 6 unresolved discussions (waiting on @bielawb, @gaelcolas, and @PlagueHO)

**Pull request merged**
