### PR TITLE
Adding task & Sample to build GuestConfig packages

### PR DESCRIPTION
**Pull request by gaelcolas**
# Pull Request

### Added

- Added the build_guestconfiguration_packages task to create GuestConfig packages using the GuestConfiguration module.
- Added GCPackage template so that you can use `Add-Sample -Sample GCPackage` to add a GC Package to your Sampler project.
- Added the gcpack meta task to call clean, build, and build_guestconfiguration_packages for you.

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/237)

### CODE REVIEW

**Comment by gaelcolas** [comment]
FTR, there's a couple of issues in the GuestConfiguration module (source are private) that I am fixing in parallel. It should work on windows when there's only 1 GCPackage per repo for now.

**Review by johlju — APPROVED** [review]
:lgtm:

Minor style comments. You can merge when fixed. 

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/237#-:-MV5TnMv482Q2oxl4kbr:b-uqbd1y)* status: all files reviewed, 7 unresolved discussions (waiting on @gaelcolas and @PlagueHO)

___
*[.build/tasks/GuestConfig.build.ps1, line 177 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5Rywu0NTxi2ee5tU-:-MV5Rywu0NTxi2ee5tU0:b61pimr) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/.build/tasks/GuestConfig.build.ps1#L177)):*
> ```
> #if
> ```

We should have space after `#`. Also upper-case 'I' in 'If' to align with the rest.
___
*[.build/tasks/GuestConfig.build.ps1, line 178 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5SIBrBuT1UPfXArrp:-MV5SIBs95604W_-Ziq-:b-iill2c) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/.build/tasks/GuestConfig.build.ps1#L178)):*
> ```
> !$IsLinux
> ```

We should use `-not $IsLinux` 
___
*[.build/tasks/GuestConfig.build.ps1, line 180 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5SNYQ-LXQhb7UI-QQ:-MV5SNYQ-LXQhb7UI-QR:bla7r9e) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/.build/tasks/GuestConfig.build.ps1#L180)):*
> ```
> # we
> ```

Upper-case 'W' in 'We' to align with the rest.
___
*[tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1, line 70 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5T317-15Y-T8CAqGf:-MV5T317-15Y-T8CAqGg:bljk48a) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1#L70)):*
> ```
> # check
> ```

Upper-case 'C' in 'Check' to align with the rest.
___
*[tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1, line 71 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5TF9cEGjEeYY9PXEe:-MV5TF9cEGjEeYY9PXEf:bp4hdbm) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1#L71)):*
> ```
> missingFilesOrFolders    = $
> ```

Whitespace here before equal sign. Also on the next row.
___
*[tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1, line 75 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5T9H68VliRN62rXFS:-MV5T9H68VliRN62rXFT:b-42db71) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1#L75)):*
> ```
> # format
> ```

Upper-case 'F' in 'Format' to align with the rest.
___
*[tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1, line 79 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5TX5F1Vawo6wvDbKs:-MV5TX5F1Vawo6wvDbKt:bk249xb) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1#L79)):*
> ```
> ( -not
> ```

We can remove whitespace after parenthesis, since there are no whitespace before the closing parenthesis.

**Comment by gaelcolas** [comment]
should be all done, waiting for build before merging.

**Review by gaelcolas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/237)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[.build/tasks/GuestConfig.build.ps1, line 177 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5Rywu0NTxi2ee5tU-:-MV6MK9o8PbhN3kORMAA:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/.build/tasks/GuestConfig.build.ps1#L177)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #if
> ```

We should have space after `#`. Also upper-case 'I' in 'If' to align with the rest.
</blockquote></details>

Done.
___
*[.build/tasks/GuestConfig.build.ps1, line 178 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5SIBrBuT1UPfXArrp:-MV6MK_9EsyImMDh8QxU:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/.build/tasks/GuestConfig.build.ps1#L178)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> !$IsLinux
> ```

We should use `-not $IsLinux` 
</blockquote></details>

Done.
___
*[.build/tasks/GuestConfig.build.ps1, line 180 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5SNYQ-LXQhb7UI-QQ:-MV6MOAO5KoN8ydBMaoM:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/.build/tasks/GuestConfig.build.ps1#L180)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> # we
> ```

Upper-case 'W' in 'We' to align with the rest.
</blockquote></details>

Done.
___
*[tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1, line 70 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5T317-15Y-T8CAqGf:-MV6MQLiBIZjvEfMirGJ:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1#L70)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> # check
> ```

Upper-case 'C' in 'Check' to align with the rest.
</blockquote></details>

Done.
___
*[tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1, line 71 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5TF9cEGjEeYY9PXEe:-MV6MZ3u1_Ha88vGWC5O:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1#L71)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> missingFilesOrFolders    = $
> ```

Whitespace here before equal sign. Also on the next row.
</blockquote></details>

Done.
___
*[tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1, line 75 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5T9H68VliRN62rXFS:-MV6MZlS1Y6cnh01Xk4q:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1#L75)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> # format
> ```

Upper-case 'F' in 'Format' to align with the rest.
</blockquote></details>

Done.
___
*[tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1, line 79 at r2](https://reviewable.io/reviews/gaelcolas/sampler/237#-MV5TX5F1Vawo6wvDbKs:-MV6MakU8Yki7uf42YEy:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/af578db2044ed7f0854d1b6d739aa40e99990c93/tests/Integration/PlasterTemplates/GCPackage/GCPackages.integration.Tests.ps1#L79)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ( -not
> ```

We can remove whitespace after parenthesis, since there are no whitespace before the closing parenthesis.
</blockquote></details>

Done.

**Pull request merged**
