### PR TITLE
Fix typos in the README.md

### PR DESCRIPTION
**Pull request by GitMje**
# Pull Request

## Pull Request (PR) description
I fixed a few typos.  

Note, it would be nice to add a mention to the [Sampler](https://www.powershellgallery.com/packages/Sampler) module on this page as well.

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/224)

### CODE REVIEW

**Comment by johlju** [comment]
@GitMje thank you for these changes. Would you mind adding an entry to the CHANGELOG.md as well? Then the tests will pass. 

> Note, it would be nice to add a mention to the [Sampler](https://www.powershellgallery.com/packages/Sampler) module on this page as well.

There is a link to the right on that page called "Project Site" that links back to this repository. Is that what you meant was missing?

**Comment by GitMje** [comment]
Thanks for the instruction, @johlju.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/224)* status: all files reviewed, 2 unresolved discussions (waiting on @GitMje)

___
*[CHANGELOG.md, line 9 at r2](https://reviewable.io/reviews/gaelcolas/sampler/224#-MQ8NQD5CnbOl7aIQRIx:-MQ8NQD5CnbOl7aIQRIy:b-ge0w24) ([raw file](https://github.com/gaelcolas/sampler/blob/f4f00ce9af665c923a2c2b2ade8e786873a392dc/CHANGELOG.md#L9)):*
> ```
> - Update the Readme.md to fix a few typos.
> ```

We should move this under the section `### Fixed` (see next comment).
___
*[CHANGELOG.md, line 11 at r2](https://reviewable.io/reviews/gaelcolas/sampler/224#-MQ8NeZiE0SXlvEb-6Ie:-MQ8NeZiE0SXlvEb-6If:bgjn4q0) ([raw file](https://github.com/gaelcolas/sampler/blob/f4f00ce9af665c923a2c2b2ade8e786873a392dc/CHANGELOG.md#L11)):*
> ```
> ### Fix
> ```

Appreciate if you would not mind renaming this section to `### Fixed`. I missed that it was named wrong in a previous PR that was reviewed. :slightly_smiling_face:

**Comment by johlju** [comment]
>  noticed that after I commented that it is there...it seems a bit hidden, but it is there.

Yes, we can't change how it looks either as it is part of PowerShell Gallery that is updated automatically from the URL in the module manifest.

**Comment by johlju** [comment]
@GitMje just two tiny review comments more, then this should be ready to merge. 🙂

**Comment by GitMje** [comment]
@johlju I've made the change to the section name and moved my comment under it.  

FYI, I also created a [new issue](https://github.com/gaelcolas/Sampler/issues/226).

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/224#-:-MQCtOI73zqyvreRMa8H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GitMje)

**Comment by johlju** [comment]
@GitMje thank you for this!

**Pull request merged**
