### PR TITLE
feat: Add support for publishing NuGet package with .NET SDK

### PR DESCRIPTION
**Pull request by pshamus**
# Pull Request

## Pull Request (PR) description

Adds support for publishing a NuGet package with the .NET SDK, if installed.

Fixes [433](https://github.com/gaelcolas/Sampler/issues/433).

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/434)

### CODE REVIEW

**Comment by pshamus** [comment]
@gaelcolas How can I mock a nonexistent command? I need to be able to test the task condition of when one of the executables does _not_ exist on the system.

**Comment by gaelcolas** [comment]
Looks like a pester issue, maybe introduced in the latest release?
Try pinning an older version of pester in RequiredModules.psd1

**Comment by pshamus** [comment]
> Looks like a pester issue, maybe introduced in the latest release? Try pinning an older version of pester in RequiredModules.psd1

Yeah, seems to pass with Pester 5.4.1.

**Comment by johlju** [comment]
I merged a change to the tests, so we can revert back to Pester 5.5 again. It should pass now.

**Comment by pshamus** [comment]
Rebased and pushed an updated commit.

**Comment by gaelcolas** [comment]
Thank you thank you. :)

**Pull request merged**
