### PR TITLE
Change supported PowerShell version to 5.0 - Fixes #85

### LINKED ISSUE #85: Allow Sampler Module to install on PowerShell 5.0
This is to enable it to be installed and used on Windows Server 2012 R2 agent in Azure DevOps.

### PR DESCRIPTION
**Pull request by PlagueHO**
## Pull Request (PR) description

- Changed module supported PowerShell version to 5.0.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/86)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @gaelcolas - I think this is because your CI is not set to trigger on PRs. Need to update the PR triggers.

**Comment by gaelcolas** [comment]
I wonder if it's a permission issue actually.
It is set for PR (at least when I raise them).

**Comment by gaelcolas** [comment]
Yay, finally found how to enable builds on PR from forks :)

**Comment by PlagueHO** [comment]
Sweet! What was the issue?

**Comment by PlagueHO** [comment]
@gaelcolas - this is failing because `CompatiblePSEditions` is only supported in PS5.0.

So to support PS5.0 I'll need to remove `CompatiblePSEditions`. So do we do this or leave it as is and state at the next community call next month that we will no longer be running automated tests on WS2012R2 and below? Maybe we ask the community for thoughts?

**Comment by gaelcolas** [comment]
There might be other field not compatible with 5.0?
I'm in favour of sticking with 5.1 but worth asking next community call.

**Comment by johlju** [comment]
It looks like it is just an issue with the `CompatiblePSEditions`, and since it does not do anything than being informational I suggest removing this property for now.

>For modules not shipped as part of Windows (i.e. modules you write or install from the gallery), this field is informational only; PowerShell does not change behavior based on the CompatiblePSEditions field
>https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_editions?view=powershell-6#the-compatiblepseditions-module-manifest-field

**Comment by gaelcolas** [comment]
Will give that a go tomorrow.

**Comment by gaelcolas** [comment]
I've just merged that into #92. closing this one, thanks.

**Pull request closed without merging**
