### PR TITLE
 Resolve-Dependency.ps1: fix MinimumPSDependVersion comparison

### PR DESCRIPTION
**Pull request by phbits**
# Pull Request

## Pull Request (PR) description

Updated MinimumPSDependVersion to use `[System.Version]::New(<string>)`. 

The only issue I've found with using this technique is using a single digit will create an error:
```powershell
PS C:\> [System.Version]::new('1')
Exception calling ".ctor" with "1" argument(s): "Version string portion was too short or too long."
At line:1 char:1
+ [System.Version]::new('1')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
```

Adding `.0` fixes this.
```powershell
PS C:\> [System.Version]::new('1.0')

Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      -1     -1
```

Could add parameter validation though that would require a separate function since the following attribute throws an error if no value is specified.
```powershell
[ValidateScript({[System.Version]::new($_)})]
```

I'm impartial on how you'd like to handle input validation. All I know is comparing version numbers works best using `System.Version`. 

### Fixed
-  Resolve-Dependency.ps1: fix MinimumPSDependVersion comparison to use System.Version

## Task list

- [ ] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [ ] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [ ] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/271)

### CODE REVIEW

**Comment by johlju** [comment]
@phbits we should update the Plaster template the same way I think: https://github.com/gaelcolas/Sampler/blob/master/Sampler/Templates/Build/Resolve-Dependency.ps1

@gaelcolas what do you think about the validation @phbits is mentioning?

**Comment by phbits** [comment]
@johlju Thanks for the suggestion. Just made the change.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/271)* status: all files reviewed, 3 unresolved discussions (waiting on @phbits)

___
*[Resolve-Dependency.ps1, line 293 at r3](https://reviewable.io/reviews/gaelcolas/sampler/271#-MY5bhGj2zYHz6zAuQJP:-MY5bhGj2zYHz6zAuQJQ:b-1ghypp) ([raw file](https://github.com/gaelcolas/sampler/blob/42939e8b7fc536e20a9ad06523343e908d395044/Resolve-Dependency.ps1#L293)):*
> ```
> | Where-Object { $_.Version -ge $([System.Version]::new($MinimumPSDependVersion)) }
> ```

The main inssue was that it didn't compare against the correct property and used `-EQ` instead of `-GE`. I think we only need to do either:

```powershell
 $psDependModule = $psDependModule | Where-Object -Property 'Version' -GE $MinimumPSDependVersion
```

or

```powershell
 $psDependModule = $psDependModule | Where-Object -FilterScript { $_.Version -ge $MinimumPSDependVersion }
```

Do we need to create a new `[System.Version]` object to compare against? :thinking: Is there a reason to use `[System.Version]`?
___
*[Resolve-Dependency.ps1, line 293 at r3](https://reviewable.io/reviews/gaelcolas/sampler/271#-MY5chqj-xLpF93l2ElI:-MY5chqj-xLpF93l2ElJ:b-jfl75n) ([raw file](https://github.com/gaelcolas/sampler/blob/42939e8b7fc536e20a9ad06523343e908d395044/Resolve-Dependency.ps1#L293)):*
> ```
> Where-Object {
> ```

We should use named parameters, `Where-Object -FilterScript { ... }`
___
*[Sampler/Templates/Build/Resolve-Dependency.ps1, line 294 at r3](https://reviewable.io/reviews/gaelcolas/sampler/271#-MY5cstn43lHAjzbuKIw:-MY5cstn43lHAjzbuKIx:bsi2kgd) ([raw file](https://github.com/gaelcolas/sampler/blob/42939e8b7fc536e20a9ad06523343e908d395044/Sampler/Templates/Build/Resolve-Dependency.ps1#L294)):*
> ```
>         $psDependModule = $psDependModule | Where-Object { $_.Version -ge $([System.Version]::new($MinimumPSDependVersion)) }
> ```

See previous comments.

**Review by phbits — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/271)* status: all files reviewed, 3 unresolved discussions (waiting on @johlju and @phbits)

___
*[Resolve-Dependency.ps1, line 293 at r3](https://reviewable.io/reviews/gaelcolas/sampler/271#-MY5bhGj2zYHz6zAuQJP:-MY5hOGG1pz1sfF2KOHS:b-56hro1) ([raw file](https://github.com/gaelcolas/sampler/blob/42939e8b7fc536e20a9ad06523343e908d395044/Resolve-Dependency.ps1#L293)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> | Where-Object { $_.Version -ge $([System.Version]::new($MinimumPSDependVersion)) }
> ```

The main inssue was that it didn't compare against the correct property and used `-EQ` instead of `-GE`. I think we only need to do either:

```powershell
 $psDependModule = $psDependModule | Where-Object -Property 'Version' -GE $MinimumPSDependVersion
```

or

```powershell
 $psDependModule = $psDependModule | Where-Object -FilterScript { $_.Version -ge $MinimumPSDependVersion }
```

Do we need to create a new `[System.Version]` object to compare against? :thinking: Is there a reason to use `[System.Version]`?
</blockquote></details>

On a past script, I spent significant time comparing versions until finally finding `[System.Version]`. Makes things much easier since this comparison is more complicated than comparing an `Int` or `string`. Being a static method makes it easy to integrate and it's already used throughout the module via casting. 

The downside is input validation. Instead of folks just specifying `1`, they'll need to specify `1.0` or `0.1`. 

After some thought and testing, the parameter could be updated as follows. This would take care of instances where no value is specified.

```powershell
    [Parameter()]
    [ValidateScript({[System.Version]::new($_)})]
    [System.String]
    $MinimumPSDependVersion = '0.0'
```

If the wrong value is specified, such as `1`, a useful error message is provided:
```powershell
D:\dev\test-param.ps1 : Cannot validate argument on parameter 'MinimumPSDependVersion'. 
Exception calling ".ctor" with "1" argument(s): "Version string portion was too short or too long."
```

I updated a local copy of `Resolve-Dependency.ps1` with the suggested parameter attributes and it runs fine. 

The part I'm not clear on is how this change will impact scripts which call `Resolve-Dependency.ps1`. I'm reviewing modules to better understand the build process and at this point cannot answer that question with 100% accuracy. And in addition, there could be folks using single digits in their data files. Food for thought from a build script newbie. :)

**Comment by johlju** [comment]
> The part I'm not clear on is how this change will impact scripts which call Resolve-Dependency.ps1.

This script is dot-sourced from within the build.ps1, and is normally not executed on its own. The parameter `MinimumPSDependVersion` is read from `Resolve-Dependency.psd1`), but it can also exist as a variable in the parent scope.

I suggest we skip parameter validation due to the script is being dot-sourced by the build.ps1 script.

When using the below code the variable `$MinimumPSDependVersion` is automatically converted to `[System.Version]` because that type is on the left-hand of the operator. 

```powershell
$psDependModule = $psDependModule | Where-Object -FilterScript { $_.Version -ge $MinimumPSDependVersion }
```

Using that and providing the value '1' it will actually give an even better error message:

```
PS > $a = Get-Module -Name 'PSDepend' -ListAvailable
PS > $a | Where-Object -FilterScript { $_.Version -ge '1' }
InvalidOperation: Could not compare "0.3.8" to "1". Error: "Cannot convert value "1" to type "System.Version". Error: "Version string portion was too short or too long. (Parameter 'input')""
```

PSDepend is using sematic versioning, so providing a value other than that should be rare. But if we want to point the user to where the error happened, if providing just '1', or '2', then we should wrap the comparison within a try-catch block.

So then the suggestion would be that we use:

```
try 
{
    $psDependModule = $psDependModule | Where-Object -FilterScript { $_.Version -ge $MinimumPSDependVersion }
}
catch 
{
    throw ('There was a problem finding the minimum version of PSDepend. Error: {0}' -f $_)
}
```

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/271)* status: all files reviewed, 1 unresolved discussion (waiting on @phbits)

___
*[Sampler/Templates/Build/Resolve-Dependency.ps1, line 293 at r4](https://reviewable.io/reviews/gaelcolas/sampler/271#-MYBc2s9ERiMircRJ8-2:-MYBc2sAA1NzGvGs5iMm:b-c8mmzh) ([raw file](https://github.com/gaelcolas/sampler/blob/5e71060f759cbea6885b0eebf8bac080ed6dae01/Sampler/Templates/Build/Resolve-Dependency.ps1#L293)):*
> ```
> $psDependModule = $psDependModule | Where-Object { $_.Version -ge $([System.Version]::new($MinimumPSDependVersion)) }
> ```

We should make the same change here as in the other file.

**Review by phbits — COMMENTED** [review]
Great catch on the type conversion! :monocle_face: :+1:

> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/271#-:-MYBnJnI6_oZPJ1NMIjV:bs7ejjp)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[Sampler/Templates/Build/Resolve-Dependency.ps1, line 293 at r4](https://reviewable.io/reviews/gaelcolas/sampler/271#-MYBc2s9ERiMircRJ8-2:-MYBnI659OJ2Wl1A2ZnX:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/5e71060f759cbea6885b0eebf8bac080ed6dae01/Sampler/Templates/Build/Resolve-Dependency.ps1#L293)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $psDependModule = $psDependModule | Where-Object { $_.Version -ge $([System.Version]::new($MinimumPSDependVersion)) }
> ```

We should make the same change here as in the other file.
</blockquote></details>

Done.

**Comment by phbits** [comment]
@johlju Thanks for the feedback! Updated the files with your try/catch approach and resolved the CHANGELOG conflict.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/271#-:-MYFKUt54kdG5BzWRN_w:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phbits)

**Comment by johlju** [comment]
@phbits thank you for your contribution! 😃

**Pull request merged**
