### PR TITLE
Update the module.tests.ps1 template

### LINKED ISSUE #465: QA module tests doesn't work correctly when module located in the git repo subfolder
### Problem description

The module.tests.ps1 doesn't correctly identify that the module root folder is different from the git top-level folder.
This problem is specific to the repos with the multiple modules in it.

### Verbose logs

```text
[-] Changelog has been updated 130ms (124ms|6ms)
   Expected 'CHANGELOG.md' to be found in collection NewModule/CHANGELOG.md, because the CHANGELOG.md must be updated with at least one entry in the Unreleased section for each PR, but it was not found.
   at $filesChanged | Should -Contain 'CHANGELOG.md' -Because 'the CHANGELOG.md must be updated with at least one entry in the Unreleased section for each PR', C:\Repos\TestSampler\NewModule\tests\QA\module.tests.ps1:82
   at <ScriptBlock>, C:\Repos\TestSampler\NewModule\tests\QA\module.tests.ps1:82
```

### How to reproduce

1. Create a new folder and execute git init in it. I used C:\Repos\TestSampler
2. Execute New-SampleModule and put the folder path from Step 1 to a DestinationPath. New-SampleModule -ModuleName NewModule -DestinationPath C:\Repos\TestSampler\ -ModuleType SimpleModule -ModuleAuthor "Authorio" -ModuleDescription "Just test sampler module"
3. Commit all changes to a main branch.
4. Create another branch.
5. Change the CHANGELOG.md file and save the changes.
6. Execute .\build.ps1 -Tasks build
7. Execute .\build.ps1 -Tasks test
8. See error.

### Expected behavior

The module.tests.ps1 should match the git top level with the ProjectPath and correctly derive the ChangeLog.md file path.

### Current behavior

The module.tests.ps1 is looking for ChangeLog.md in the git top-level folder.

### Suggested solution

Add  `$gitRelatedModulePath` to a BeforeAll section
```PowerShell
$gitTopLevelPath = (&git rev-parse --show-toplevel)
$gitRelatedModulePath = (($projectPath -replace [regex]::Escape([IO.Path]::DirectorySeparatorChar), '/') -replace $gitTopLevelPath, '').Trim('/') + '/'
```

Change the `$filesChanged ` and `$filesStagedAndUnstaged` in the `It 'Changelog has been updated'`
```PowerShell
$filesChanged = (&git @('diff', "$defaultBranchCommit...$headCommit", '--name-only')) -replace "^$gitRelatedModulePath", ""
$filesStagedAndUnstaged = (&git @('diff', 'HEAD', '--name-only') 2>&1) -replace "^$gitRelatedModulePath", ""
```

### Operating system the target node is running

```text
OsName               : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, uk-UA}
Also tested on Win 10 Pro
```

### PowerShell version and build the target node is running

```text
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module version used

```text
Sampler 0.117.0 C:\Repos\TestSampler\NewModule\output\RequiredModules\Sampler\0.117.0\Sampler.psd1
```

### PR DESCRIPTION
**Pull request by Sidoran**
# Pull Request

## Pull Request (PR) description
- Update template for module.tests.ps1.

### Fixed
- Fixes #465 

## Task list

- [X] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [X] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [X] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [X] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/466)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/466)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Sidoran)

*[a discussion](https://reviewable.io/reviews/gaelcolas/Sampler/466#-Ns2rQaQCQ9af3XhcBoG:-Ns2rQaQCQ9af3XhcBoH:b-f8hb9u) (no related file):*
I think this need to be changed to single out only the files in the diff that belongs to the actual module being tested.
So `$filesChanged` and `$filesStagedAndUnstaged` should not contain other files.

For example after using the provided repro example in the issue by adding a module project `NewModule` a second module project is added into the folder `SecondModule`. If using the suggested change and changing `Get-Something.ps1` under the folder SecondModule I'm getting this error when running the QA tests for the NewModule. It says I need to add a CHANGELOG.md in NewModule because a file was change under SecondModule.

```
Running tests from '/Users/johlju/source/HelpUsers/sidoran/TestSampler/NewModule/tests/QA/module.tests.ps1'
Describing Changelog Management
  [-] Changelog has been updated 223ms (220ms|3ms)
   Expected 'CHANGELOG.md' to be found in collection SecondModule/source/Public/Get-Something.ps1, because the CHANGELOG.md must be updated with at least one entry in the Unreleased section for each PR, but it was not found.
   at $filesChanged | Should -Contain 'CHANGELOG.md' -Because 'the CHANGELOG.md must be updated with at least one entry in the Unreleased section for each PR', /Users/johlju/source/HelpUsers/sidoran/TestSampler/NewModule/tests/QA/module.tests.ps1:86
   at <ScriptBlock>, /Users/johlju/source/HelpUsers/sidoran/TestSampler/NewModule/tests/QA/module.tests.ps1:86
```

Also if there are a module project in the root of TestSampler, and there is a module project in a the subfolder SecondModule, and a the same file as above is changed I get the below error. It says I need to add a CHANGELOG.md in the root module project because a file was change under SecondModule.

```
Running tests from '/Users/johlju/source/HelpUsers/sidoran/TestSampler/tests/QA/module.tests.ps1'
Describing Changelog Management
  [-] Changelog has been updated 199ms (194ms|5ms)
   Expected 'CHANGELOG.md' to be found in collection SecondModule/source/Public/Get-Something.ps1, because the CHANGELOG.md must be updated with at least one entry in the Unreleased section for each PR, but it was not found.
   at $filesChanged | Should -Contain 'CHANGELOG.md' -Because 'the CHANGELOG.md must be updated with at least one entry in the Unreleased section for each PR', /Users/johlju/source/HelpUsers/sidoran/TestSampler/tests/QA/module.tests.ps1:86
   at <ScriptBlock>, /Users/johlju/source/HelpUsers/sidoran/TestSampler/tests/QA/module.tests.ps1:86
```

___
___
*[`Sampler/Templates/Sampler/module.tests.ps1.template` line 26 at r1](https://reviewable.io/reviews/gaelcolas/Sampler/466#-Ns2uAWvAXkINGjihx9G:-Ns2uAWvAXkINGjihx9H:b-thvnsq) ([raw file](https://github.com/gaelcolas/Sampler/blob/4b80b0570da5b8b4d5c473d00e23159fde97b496/Sampler/Templates/Sampler/module.tests.ps1.template#L26)):*
> ```
>     # Convert-Path required for PS7 or Join-Path fails
>     $projectPath = "$($PSScriptRoot)\..\.." | Convert-Path
> ```

If the module project is not using git then this should be excluded from the generated file. See example in code how the it-block is also excluded.

```
<%
if ($PLASTER_PARAM_UseGit -eq 'true')
{
@'
# .... code
'@
}
%>
```

**Comment by johlju** [comment]
> Also if there are a module project in the root of TestSampler, and there is a module project in a the subfolder SecondModule

This scenario might be difficult to determine without scanning each subfolder 🤔 So maybe for this case we just document that it is not recommended to have a module project in the root folder at the same time as having module projects in subfolders. 🤔

**Comment by Sidoran** [comment]
Hi @johlju, TY for paying attention to this issue. Modifying several modules simultaneously in one multi-module repo is not a good idea, but the code should support it. I changed the code, and from now each module folder will be checked separately.

About the second case (The repo with the module in root and the other module in a subfolder). It would be tough to divide which module file is related (to the root level or the module in a subfolder). I am inclined not to support the given type of multi-module repo to not deeper into a folder structure and all other items. I would happily update the documentation with the info that a given type of repo may generate false positive errors. Can you please point me to where I can add this info?

**Comment by johlju** [comment]
> I would happily update the documentation with the info that a given type of repo may generate false positive errors. Can you please point me to where I can add this info?

Suggest adding a new section under https://github.com/gaelcolas/Sampler/blob/main/README.md#how-to-create-a-new-project

**Comment by Sidoran** [comment]
The Readme.md file has been updated with the multi-module information.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/466#-:-NumV2It8Ia58bP942gI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Sidoran)

**Pull request merged**
